@startuml PharmaNet_OAuth2_HNClient_Flow
autonumber
    actor Citizen
    Browser <-- HealthGateway : Begin
    Browser <-> KeyCloak : OIDC Login Flow
    Citizen -> Browser : Get Medications
    Browser -> HealthGateway_PatientAPI : Get PHN (JWT, HDID)
    HealthGateway_PatientAPI <-> KeyCloak : Check Authorization (JWT)
    HealthGateway_PatientAPI <-> HCIM : HCIM_IN_GetDemographics 
    Browser <-- HealthGateway_PatientAPI : Return PHN
    Browser -> HealthGateway_MedicationsAPI : Get Medications (JWT, PHN)
    HealthGateway_MedicationsAPI -> KeyCloak : Check Authorization (JWT)
    HealthGateway_MedicationsAPI <-> KeyCloak : Request Client Credentials Grant Access Token (clientID, secret)
    HealthGateway_HNClient <-> KeyCloak : Validate Access Token  (Token)
    HealthGateway_MedicationsAPI -> HealthGateway_HNClient : Request Patient Medication Profile (Token, TRP)
    HealthGateway_HNClient <-> PharmaNet : Connect to PharmaNet using secure endpoint route (HNSecure)
    HealthGateway_HNClient -> PharmaNet : Request Patient Medication Profile TRP
    HealthGateway_MedicationsAPI <-- HealthGateway_HNClient : Return TRP Response
    Browser <-- HealthGateway_MedicationsAPI : Return Medications (JSON)
@enduml
