version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /services/medications/k6_meds.js
    volumes:
      - ../../services/medications:/services/medications
      - ../../inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_VUS=${HG_VUS}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
