name: 1.0.0$(Rev:.r) #Build number

pr: none

resources:
    pipelines:
      - pipeline: Common
        source: Common
        trigger:
          branches:
          - dev

trigger:
    batch: "true"
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/JobScheduler

extends:
  template: /Build/hg.yaml
  parameters:
    Application: JobScheduler
    OpenShiftName: hangfire
    DotNetTests: false
    FunctionalTests: false
    NPMInstall: false
    NPMTests: false
