name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/JobScheduler
  App.Name: hangfire
  App.UnitTests: $(App.Home)/test/unit
  App.FunctionalTests: $(App.Home)/test/functional

pr: none

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/JobScheduler
     - Apps/Common
     - Apps/Database

pool:
  name: 'HealthGateway'

steps:
- task: DotNetCoreCLI@2
  displayName: Run dotnet Tests
  inputs:
    command: 'test'
    projects: '$(App.UnitTests)/JobSchedulerTests.csproj'
    testRunTitle: 'JobScheduler Tests'
  enabled: 'false'

- script: |
    set -e
    dotnet test test/unit/JobScheduler.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger:"xunit;LogFileName=results.xml" -r ./xUnitResults 
    dotnet sonarscanner begin /d:sonar.verbose=false /k:"hangfire_dev" /d:sonar.host.url="https://sonarqube-gateway.pathfinder.gov.bc.ca" /d:sonar.login="$(sonar.login)" /d:sonar.scm.disabled="true" /d:sonar.coverage.exclusions="**Tests*.cs, **/Common/**" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.cs.xunit.reportsPaths="**/xUnitResults/results.xml" 
    dotnet build    
    dotnet sonarscanner end /d:sonar.login="$(sonar.login)"
    echo "$@" >&2
  displayName: 'Perform Static Code Analysis'
  continueOnError: 'false'
  workingDirectory: $(App.Home)
  enabled: 'false'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(App.UnitTests)/JobSchedulerTests.csproj'
    testRunTitle: 'Build JobScheduler Tests'
  enabled: 'false'

- task: DotNetCoreCLI@2
  displayName: Building and Publishing JobScheduler
  inputs:
    modifyOutputPath: false
    command: 'publish'
    publishWebProjects: false
    projects: '$(App.Home)/src'
    arguments: '-o $(Build.BinariesDirectory)'
    zipAfterPublish: false

- script: |
    set -e
    cat $(App.Home)/src/appsettings.json
    cp $(App.Home)/Dockerfile $(Build.BinariesDirectory)
    cat $(Build.BinariesDirectory)/appsettings.json
    oc process -f $(Build.SourcesDirectory)/Tools/BaseBuild/build.yaml -p NAME=$(App.Name) | oc apply -f -
    oc start-build $(App.Name) --wait --follow --from-dir $(Build.BinariesDirectory) 
    oc tag $(App.Name):latest $(App.Name):$(Build.BuildNumber)
    echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
  displayName: 'Build OpenShift Image and push to Image Stream'

- task: CopyFiles@2
  displayName: Copy Functional Tests to Staging
  inputs:
    SourceFolder: '$(App.FunctionalTests)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  enabled: 'false'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
