name: PR$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/JobScheduler

trigger: none  

extends:
  template: /Build/hg.yaml
  parameters:
    Application: JobScheduler
    OpenShiftName: hangfire
    DotNetTests: false
    FunctionalTests: false
    NPMInstall: false
    NPMTests: false
