name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/JobScheduler
      - Apps/DBMaintainer

trigger: none

extends:
  template: /Build/hg.yaml
  parameters:
    Application: JobScheduler
    ImageName: hangfire
    DotNetTests: false
    NPMInstall: false
