version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /gateway_api/notes/k6_notes.js
    volumes:
      - ../../gateway_api/notes:/gateway_api/notes
      - ../../inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_VUS=${HG_VUS}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
