name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/WebClient
  App.Name: webclient

pr: none

trigger:
 batch: 'true'
 branches:
   include:
     - dev
 paths:
   include:
     - Apps/WebClient/src
     - Apps/WebClient/test
     - Apps/WebClient/azure/build.yaml
     - Apps/WebClient/Dockerfile
 
pool:
  name: 'HealthGateway'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(App.Home)/src'

- script: |
    dotnet test test/test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    npm --prefix src test
    dotnet sonarscanner begin /k:"webclient_dev" /v:$(Build.BuildNumber) /d:sonar.host.url="https://sonarqube-gateway.pathfinder.gov.bc.ca" /d:sonar.login="70a09cf96a40f256e999ecfa7a59359f06167b16" /d:sonar.coverage.exclusions="**Tests*.cs" /d:sonar.testExecutionReportPaths="src/jest.out/test-report.xml" /d:sonar.typescript.lcov.reportPaths="jest.out/lcov.info" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.verbose=true
    dotnet build    
    dotnet sonarscanner end /d:sonar.login="70a09cf96a40f256e999ecfa7a59359f06167b16"
    echo "$@" >&2
  displayName: 'Perform static analisis'
  continueOnError: 'false'
  workingDirectory: $(Build.SourcesDirectory)/Apps/WebClient

- task: DotNetCoreCLI@2
  inputs:
    modifyOutputPath: false
    command: 'publish'
    publishWebProjects: false
    projects: '$(App.Home)/src'
    arguments: '-o $(Build.BinariesDirectory)'
    zipAfterPublish: false

#- script: |
#    pushd $(App.Home)
#    cp Dockerfile $(Build.BinariesDirectory)
#    pushd src
#    dotnet publish -o $(Build.BinariesDirectory)
#    popd
#    popd
#  displayName: 'Restore and publish .Net App'

- script: |
    cp $(App.Home)/Dockerfile $(Build.BinariesDirectory)
    oc process -f $(Build.SourcesDirectory)/Tools/BaseBuild/build.yaml -p NAME=$(App.Name) | oc apply -f -
    oc start-build $(App.Name) --wait --follow --from-dir $(Build.BinariesDirectory) 
    oc tag $(App.Name):latest $(App.Name):$(Build.BuildNumber)
    echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
  displayName: 'Build OpenShift Image and push to Image Stream'

- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'

