name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
    batch: "true"
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/WebClient
        - Apps/Common
        - Apps/Database

pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: WebClient
    DotNetTests: true
    FunctionalTests: false
    NPMInstall: true
    NPMTests: true

