name: PR$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/WebClient
        # - Apps/Common
        # - Apps/Database

trigger: none
        
pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: WebClient
    DotNetTests: true
    FunctionalTests: false
    NPMInstall: true
    NPMTests: true

