name: PR$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Encounter
        # - Apps/Common
        # - Apps/Database

trigger: none
        
pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Encounter
    DotNetTests: true
    NPMInstall: false
    NPMTests: false

