# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/AdminWebClient/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Apps/AdminWebClient/src/ClientApp" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Common/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/DBMaintainer" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Encounter/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Immunization/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/JobScheduler/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"
      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Laboratory//src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"      

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Medication/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"
      
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/Patient/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"  

  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Apps/WebClient/src" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/Apps/WebClient/src/ClientApp" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - "sslaws"
      - "FuriousLlama"
      - "tiagograf-AOT"
      - "leobcgov"
