apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: patroni
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "${PG_VERSION}"
objects:
  #Postgres ImageStream is created if it doesn't already exist
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: postgres
    spec:
      lookupPolicy:
        local: false

  - apiVersion: v1
    kind: ImageStreamTag
    lookupPolicy:
      local: false
    metadata:
      name: postgres:${PG_VERSION}
    tag:
      annotations: null
      from:
        kind: DockerImage
        name: docker.io/library/postgres:${PG_VERSION}
      importPolicy:
        scheduled: true
      name: "${PG_VERSION}"
      referencePolicy:
        type: Source

  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${OUT_VERSION}"
      postCommit: {}
      resources: {}
      source:
        contextDir: ${DOCKER_CONTEXT}
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URI}
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: postgres:${PG_VERSION}
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0

parameters:
  - name: NAME
    value: patroni
  - name: SUFFIX
    value: "-pg11"
  - name: OUT_VERSION
    description: Ouput version
    value: "v11-latest"
  - name: GIT_URI
    value: https://github.com/bcgov/healthgateway.git
  - name: GIT_REF
    value: dev
  - name: DOCKER_CONTEXT
    value: Tools/Postgres/docker
  - name: PG_VERSION
    value: "11"
