FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
ARG APP=WebClient
ARG NODE_VERSION=v10.13.0
USER root
# Fetch stock nodejs and install
RUN mkdir -p /usr/local/lib/nodejs && \
    cd /usr/local/lib/nodejs && \
    echo "Downloading https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz" && \
    curl -sL https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz | tar -xzv && \
    rm -f node-${NODE_VERSION}-linux-x64.tar.gz

RUN adduser --disabled-password --gecos "Test user" installer
USER installer
ENV PATH=/usr/local/lib/nodejs/node-${NODE_VERSION}-linux-x64/bin:$PATH

WORKDIR /home/installer
#Copy Required Projects
COPY --chown=installer:installer Common Common
COPY --chown=installer:installer Database Database
#COPY --chown=installer:installer DBMaintainer DBMaintainer
COPY --chown=installer:installer $APP $APP	

WORKDIR /home/installer/$APP
#RUN dotnet restore
RUN rm src/*.local.json && \
    cd src/ClientApp && \
    rm -rf node_modules && \
    npm install && \
    cd ../.. && \
    dotnet publish -o ../../out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
ENV ASPNETCORE_URLS=http://+:8080
WORKDIR /app
COPY --from=build /home/installer/out ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "WebClient.dll"]
