FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ARG APP=WebClient
ARG NODE_VERSION=v12.13.1
USER root
# Fetch stock nodejs and install
RUN mkdir -p /usr/local/lib/nodejs && \
    cd /usr/local/lib/nodejs && \
    echo "Downloading https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz" && \
    curl -sL https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz | tar -xzv && \
    rm -f node-${NODE_VERSION}-linux-x64.tar.gz

RUN adduser --disabled-password --gecos "Test user" installer

ENV PATH=/usr/local/lib/nodejs/node-${NODE_VERSION}-linux-x64/bin:$PATH

# Update the version of `npm` that came with the packages above
# and install a few additional tools.
RUN npm i -g npm@latest yarn@latest nsp@latest nodemon@latest && \
    rm -rf ~/.npm && \
    node -v && \
    npm -v

USER installer

WORKDIR /home/installer
#Copy Required Projects
COPY --chown=installer:installer Common Common
COPY --chown=installer:installer Database Database
#COPY --chown=installer:installer DBMaintainer DBMaintainer
COPY --chown=installer:installer $APP $APP	

WORKDIR /home/installer/$APP
#RUN dotnet restore
RUN rm src/*.local.json && \
    cd src/ClientApp && \
    rm -rf node_modules && \
    npm install && \
    cd ../../ && \
    dotnet publish -o ../out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
ENV ASPNETCORE_URLS=http://+:8080
WORKDIR /app
COPY --from=build /home/installer/out ./
EXPOSE 8080
ENTRYPOINT ["dotnet", "WebClient.dll"]
