name: 1.0.0$(Rev:.r) #Build number

pr: none

resources:
  pipelines:
    - pipeline: Common
      source: Common
      trigger:
        branches:
          - dev

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Patient

pool:
  name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Patient
    DotNetTests: true
    NPMInstall: false
    NPMTests: false
