Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: Production

OpenShift:
  Environment: production

resources: 
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 3
