Application:
  Environment:
    ASPNETCORE_ENVIRONMENT: hgtest

OpenShift:
  Environment: test

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 20m
    memory: 512Mi

autoscaling:
  enabled: true
  