# Default values for clinicaldocument.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

Application:
  Port: 8080
  Configuration:
    HealthGateway_ConnectionStrings__GatewayConnection: common-config
  Secrets:
    HealthGateway_PatientService__ClientRegistry__ClientCertificate__Password: common-secrets
    HealthGateway_RedisConnection: common-secrets
  Environment:
    ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

OpenShift:
  Environment: ${ENVIRONMENT}
  ImageProject: 0bd5ad-tools

image:
  repository: clinicaldocument
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  port: 8080


ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: ${CPU.LIMIT}
    memory: ${MEMORY.LIMIT}
  requests:
    cpu: ${CPU.REQUEST}
    memory: ${MEMORY.REQUEST}

autoscaling:
  enabled: false
  podDisruptionMin: 2
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
