pr: none
trigger: none
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - dev
pool:
  name: "HealthGateway"

jobs:
  - job: AnalyzeProjects
    timeoutInMinutes: 120
    steps:
      - script: |
          set -e
          export SONAR_SCANNER_OPTS="-Xmx3072m"
          npm --prefix WebClient/src/ClientApp install --only=dev
          npm --prefix WebClient/src/ClientApp test
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            --logger:"xunit;LogFileName=results.xml"
          dotnet sonarscanner begin \
            /o:bcgov-sonarcloud \
            /k:bcgov_healthgateway \
            /n:"HealthGateway" \
            /d:sonar.login="$(common.login)" \
            /s:$(Build.SourcesDirectory)/Apps/sonar-config.xml
          dotnet build    
          dotnet sonarscanner end /d:sonar.login="$(common.login)"
          echo "$@" >&2
        displayName: "Perform Static Code Analysis"
        continueOnError: true
        workingDirectory: $(Build.SourcesDirectory)/Apps/
        enabled: "true"

      - script: |
          curl '-X' POST '-H' 'Content-Type: application/json' '--data' '{"icon_emoji":":cloud_lightning:","text":"SonarCloud Analysis Failed."}' https://chat.pathfinder.gov.bc.ca/hooks/WEHBAtxe6ufWYj2FR/2MMMbS9btPZxtrbgPckiuCqqLzsnEuuWmozKjtY8fXrWHjoa
        displayName: "On Fail"
        condition: failed()
