name: $(date:yyyy).$(date:MM).$(date:dd).$(rev:r)

pr: none
trigger: none
#Build variables
variables:
  - group: Cypress
  - group: Azure DB - Dev
  - group: Admin - Dev
  - group: Phsa - Dev

jobs:
  - job: "Admin_Functional_Tests"
    pool:
      vmImage: "ubuntu-latest"
    displayName: "Admin Functional Tests"
    steps:
    - task: Bash@3
      displayName: 'Seed Databases'
      inputs:
        targetType: filePath
        filePath: './Tools/Pipelines/azp_seedDb.sh'
        arguments: Testing/functional/tests
