name: $(date:yyyy).$(date:MM).$(date:dd).$(rev:r)

pr: none
trigger: none
#Build variables
variables:
  - group: Cypress
  - group: Azure DB - Dev
  - group: Admin - Dev
  - group: Phsa - Dev

jobs:
  - job: "Admin_Seed"
    pool: 
      name: "HealthGatewayDev"
    displayName: "Re-seed DB and PHSA data for Admin"
    steps:
    - task: Bash@3
      displayName: 'Re-seed DB and PHSA data for Admin'
      inputs:
        targetType: filePath
        filePath: './Tools/Pipelines/scripts/azp_seedDb.sh'
        arguments: Testing/functional/tests
      env: # Required secrets for seed db script
        DB_PASSWORD: $(db.password)
        ADMIN_KEYCLOAK_SECRET: $(admin.keycloak.secret)
        PHSA_KEYCLOAK_DEVTOOLS_SECRET: $(phsa.keycloak.devtools.secret)
  - job: "Admin_Tests"
    dependsOn: "Admin_Seed"
    pool: 
      vmImage: "ubuntu-latest"
    displayName: "Admin Functional Tests"  
    strategy:
      parallel: 9
    steps:
    - task: Bash@3
      displayName: 'Run Admin Functional Tests'
      inputs:
        targetType: filePath
        filePath: './Tools/Pipelines/scripts/azp_runAdminFunctionalTests.sh'
        arguments: Apps/Admin/Tests/Functional $(Build.BuildNumber)-$(System.JobAttempt) "dev,$(Build.Reason)"
      env: # Required environment settings and secrets for admin tests
        TERM: xterm
        KEYCLOAK_PASSWORD: $(keycloak.pw)
        IDIR_PASSWORD: $(idir.password)
        KEYCLOAK_ADMIN_SECRET: $(keycloak.admin.secret)
        CYPRESS_ADMIN_KEY: $(cypress.admin.key)

#Future Use
        # BCSC_PW: $(bcsc.pw)
        # CYPRESS_ADMIN_KEY: $(cypress.admin.key)
        # CYPRESS_KEY: $(cypress.key)
        # IDIR_PASSWORD: $(idir.password)
        # KEYCLOAK_ADMIN_SECRET: $(keycloak.admin.secret)
        # KEYCLOAK_PHSA_CLIENT: $(keycloak.phsa.client)
        # KEYCLOAK_PHSA_SECRET: $(keycloak.phsa.secret)
        # KEYCLOAK_PW: $(keycloak.pw)
        # PHONENUMBER: $(phoneNumber)