name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Admin
#      - Apps/Common
#      - Apps/Database

trigger: none

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Admin
    WASMBuild: true
    DotNetTests: false
    NPMInstall: false
