apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-netpol
spec:
  podSelector:
    matchLabels:
      app: redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - port: 6379
          protocol: TCP
        - port: 26379
          protocol: TCP
    - from:
        - podSelector:
            matchLabels: {}
      ports:
        - port: 6379
          protocol: TCP
        - port: 26379
          protocol: TCP
