apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-rs-netpol
  labels: {{ include "standard.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-rs
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-rs
      ports:
        - port: {{ .Values.redisPort }}
          protocol: TCP
        - port: {{ .Values.sentinelPort }}
          protocol: TCP
    - from:
        - podSelector:
            matchLabels: {}
      ports:
        - port: {{ .Values.redisPort }}
          protocol: TCP
        - port: {{ .Values.sentinelPort }}
          protocol: TCP
