kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-rs-secret
  labels: {{ include "standard.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.password | required "Values.password" | quote }}
