apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rs-svc
  labels: {{ include "standard.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sentinelPort }}
      targetPort: {{ .Values.sentinelPort }}
      name: sentinel
  selector:
    app: {{ .Release.Name }}-rs
