{{ $image := print .Values.imageRepository ":" .Values.imageTag }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-rs
  labels: {{ include "standard.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-rs-svc
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rs
  template:
    metadata:
      labels: {{ include "standard.labels" . | nindent 8 }}
        app: {{ .Release.Name }}-rs
    spec:
      initContainers:
        - name: config
          image: {{ $image }}
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          env:
            - name: REDIS_NODES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-rs-config
                  key: REDIS_NODES
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rs-secret
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              value: {{ .Values.redisPort | required "Values.redisPort" | quote }}
            - name: SENTINEL_PORT
              value: {{ .Values.sentinelPort | required "Values.sentinelPort" | quote }}
            - name: REDIS_SERVICE
              value: {{ .Release.Name }}-rs-svc
            - name: NODE_NAME_PREFIX
              value: {{ .Release.Name }}-rs
            - name: SENTINEL_SET
              value: {{ .Values.setName | default "mymaster" }}
          command: ["sh", "-c", "/scripts/init.sh"]
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/
            - name: config
              mountPath: /tmp/redis/
            - name: scripts
              mountPath: /scripts/
      containers:
        - name: redis-sentinel
          image: {{ $image }}
          lifecycle:
            preStop:
              exec:
                command:
                  ["/bin/sh", "-c", "redis-cli -h $HOSTNAME shutdown save"]
          livenessProbe:
            exec:
              command:
                [
                  "/bin/sh",
                  "-c",
                  'test "$(redis-cli -h $HOSTNAME ping)" = "PONG"',
                ]
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                [
                  "/bin/sh",
                  "-c",
                  'test "$(redis-cli -h $HOSTNAME ping)" = "PONG"',
                ]
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          command: ["/scripts/start.sh"]
          ports:
            - containerPort: {{ .Values.redisPort }}
              name: redis
            - containerPort: {{ .Values.sentinelPort }}
              name: sentinel
          env:
            - name: REDISCLI_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rs-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data
            - name: redis-config
              mountPath: /etc/redis/
            - name: config
              mountPath: /tmp/redis/
            - name: scripts
              mountPath: /scripts/
          resources: {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: redis-config
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-rs-config
            defaultMode: 0777
            items:
              - key: redis_init.sh
                path: redis_init.sh
              - key: sentinel_init.sh
                path: sentinel_init.sh
              - key: start.sh
                path: start.sh
              - key: init.sh
                path: init.sh
        - name: config
          configMap:
            name: {{ .Release.Name }}-rs-config
            items:
              - key: redis.conf
                path: redis.conf
