name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Tools/BaseImage/
  App.Name: hg-base

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily Base Image Build"
    branches:
      include: 
        - dev
    always: true

pr: none

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Tools/BaseImage

pool:
  name: "HealthGateway"

steps:
  - script: |
      set -e
      oc process -f $(App.Home)/build.yaml | oc apply -f -
      oc start-build $(App.Name) --wait --follow 
      oc tag $(App.Name):latest $(App.Name):$(Build.BuildNumber)
      echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
    displayName: "Build OpenShift Image and push to Image Stream"

  - task: PublishPipelineArtifact@0
    displayName: "Publish Pipeline Artifact"
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)"
