name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  - group: Secrets
  - name: App.Home
    value: $(Build.SourcesDirectory)/Tools/BaseImage/
  - name: App.Name 
    value: hg-base

schedules:
  - cron: "0 0 * * *"
    displayName: "Health Gateway Base Image Build"
    branches:
      include: 
        - dev
    always: true

pr: none

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Tools/BaseImage

pool:
  vmImage: "ubuntu-20.04"

steps:
- task: Docker@2
  displayName: "Build Image and push to Docker"
  inputs:
    containerRegistry: 'docker-health'
    repository: '$(DockerRepo)/$(App.Name)'
    Dockerfile: Tools/BaseImage/docker/Dockerfile
    buildContext: '$(Build.BinariesDirectory)'
    tags: |
     $(Build.BuildNumber)
     latest

- bash: |
   docker tag $(DockerRepo)/$(App.Name):$(Build.BuildNumber) $(ImageRegistry)/$(SilverLicense)-tools/$(App.Name):$(Build.BuildNumber)
   docker tag $(DockerRepo)/$(App.Name):$(Build.BuildNumber) $(ImageRegistry)/$(SilverLicense)-tools/$(App.Name):latest
   docker login $(ImageRegistry) --username=azure --password=$(OpenShiftToken)
   docker push $(ImageRegistry)/$(SilverLicense)-tools/$(App.Name):$(Build.BuildNumber)
   docker push $(ImageRegistry)/$(SilverLicense)-tools/$(App.Name):latest
  displayName: Tag and Push to OpenShift

- task: PublishPipelineArtifact@0
  displayName: "Publish Pipeline Artifact"
  inputs:
    targetPath: "$(Build.ArtifactStagingDirectory)"
  enabled: false