name: 1.0.0$(Rev:.r) #Build number

#Build variables
variables:
  - group: Secrets
  - name: App.Home
    value: $(Build.SourcesDirectory)/Tools/BaseImage/
  - name: App.Name
    value: hg-base

schedules:
  - cron: "0 0 * * *"
    displayName: "Health Gateway Base Image Build"
    branches:
      include:
        - dev
    always: true

pr: none

trigger:
  batch: true
  branches:
    include:
      - dev
  paths:
    include:
      - Tools/BaseImage

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: Docker@2
    displayName: "Build Image and push to Docker"
    inputs:
      containerRegistry: "docker-health"
      repository: "$(DockerRepo)/$(App.Name)"
      Dockerfile: Tools/BaseImage/docker/Dockerfile
      buildContext: "$(Build.SourcesDirectory)/Tools/BaseImage"
      tags: |
        $(Build.BuildNumber)
        latest

  # Debug: Verify certificates inside the image
  - script: |
      echo "Running debug validation on Docker image..."
      docker run --rm "$(DockerRepo)/$(App.Name):latest" bash -c "
        echo 'Listing files in /etc/ssl/certs/custom:' && \
        ls -l /etc/ssl/certs/custom && \
        echo 'Listing files in /usr/local/share/ca-certificates:' && \
        ls -l /usr/local/share/ca-certificates && \
        echo 'Validating certificates using openssl:' && \
        openssl x509 -in /usr/local/share/ca-certificates/tls-root.crt -text -noout
      "
    displayName: "Debug: Verify Certificates in Image"
