# APS netpol to allow it to access API pods
{{- $name := print $.Release.Name "-aps" -}}
{{- $namespace := $.Values.namespace | default $.Release.Namespace -}}
{{- $labels := include "standard.labels" . -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $name }}-netpol
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      role: api
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              environment: {{ .Values.apsConfig.env }}
              name: {{ .Values.apsConfig.namespace }}
