# commonly shared secrets
{{- $name := printf "%s-%s" $.Release.Name "common-secrets" -}}
{{- $namespace := $.Values.namespace | default $.Release.Namespace }}
{{- $labels := include "standard.labels" . -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
data: {{ include "all.encoded" (($.Files.Get $.Values.commonSecrets.file) | fromYaml) | nindent 2 }}
