# common volume to manage asp.net data protection keys
{{- $name := print $.Release.Name "-data-protection" }}
{{- $namespace := $.Values.namespace | default $.Release.Namespace -}}
{{- $labels := include "standard.labels" . }}
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "512Mi"
