# postgres predefined secrets
{{- $name := print .Release.Name "-patroni" }}
{{- $namespace := $.Values.namespace | default $.Release.Namespace -}}
{{ $secrets := ($.Files.Get $.Values.patroniSecrets.file | fromYaml) }}
{{- $labels := include "standard.labels" $ }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels: {{ $labels | nindent 4 }}
data: {{ include "all.encoded" $secrets | nindent 2 }}
