replicaCount: 6

image:
  repository: redis
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

podAnnotations: {}

service:
  redis:
    port: 6379
  gossip: 
    port: 16379

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 20m
    memory: 64Mi
    storage: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
