name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Testing/functional
      - Apps/Admin/Tests/Functional
variables:
  Tests.Path: $(Build.SourcesDirectory)/Testing/functional/tests
  Admin.Path: $(Build.SourcesDirectory)/Apps/Admin/Tests/Functional

jobs:
  - job: "PackageTests"
    pool:
      vmImage: "ubuntu-20.04"
    displayName: "Packaging Functional Tests"
    steps:
      - script: |
          set -e
          echo Creating Artifact
          echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
          mkdir $(Build.ArtifactStagingDirectory)/admin $(Build.ArtifactStagingDirectory)/gateway
        displayName: "Create Trigger Build Artifact"

      - task: CopyFiles@2
        displayName: "Copying Gateway Functional Tests to Staging"
        inputs:
          SourceFolder: "$(Tests.Path)"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/gateway"

      - task: CopyFiles@2
        displayName: "Copying Admin Functional Tests to Staging"
        inputs:
          SourceFolder: "$(Admin.Path)"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)/admin"

      - task: PublishPipelineArtifact@0
        displayName: "Publishing Functional Tests"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)"
