name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Testing/functional
variables:
  Tests.Path: $(Build.SourcesDirectory)/Testing/functional/tests

jobs:
  - job: "PackageTests"
    pool:
      vmImage: "ubuntu-20.04"
    displayName: "Packaging Functional Tests"
    steps:
      - script: |
          set -e
          echo Creating Artifact
          echo `date` > $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).txt
        displayName: "Create Trigger Build Artifact"

      - task: CopyFiles@2
        displayName: "Copying Functional Tests to Staging"
        inputs:
          SourceFolder: "$(Tests.Path)"
          Contents: "**"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

      - task: PublishPipelineArtifact@0
        displayName: "Publishing Functional Tests"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)"
