// Correlates 2-letter country codes with country names for addressing
// ISO 3166 Alpha-2 Format: [2 letter Country Code]: [Country Names]
// Sorted alphabetical by country code
export const Countries: Record<string, string[]> = {
    AD: ["Andorra"],
    AE: ["United Arab Emirates"],
    AF: ["Afghanistan"],
    AG: ["Antigua and Barbuda"],
    AI: ["Anguilla"],
    AL: ["Albania"],
    AM: ["Armenia"],
    AO: ["Angola"],
    AQ: ["Antarctica"],
    AR: ["Argentina"],
    AS: [
        "American Samoa",
        "Aunu'u and Manua Islands (included in American Samoa)",
        "Swains Island (included in American Samoa)",
        "Tutuila Island (included in American Samoa)",
    ],
    AT: ["Austria"],
    AU: [
        "Australia",
        "Lord Howe Island (included in Australia)",
        "Tasmania (included in Australia)",
    ],
    AW: ["Aruba"],
    AX: ["Aland Islands"],
    AZ: ["Azerbaijan"],
    BA: ["Bosnia–Herzegovina"],
    BB: ["Barbados"],
    BD: ["Bangladesh"],
    BE: ["Belgium"],
    BF: ["Burkina Faso"],
    BG: ["Bulgaria"],
    BH: ["Bahrain"],
    BI: ["Burundi"],
    BJ: ["Benin"],
    BL: ["Saint Barthélémy"],
    BM: ["Bermuda"],
    BN: ["Brunei Darussalam"],
    BO: ["Bolivia"],
    BQ: [
        "Dutch Caribbean (formerly Netherlands Antilles)",
        "Bonaire (included in Dutch Caribbean (formerly Netherlands Antilles))",
        "Netherlands Antilles (now known as Dutch Caribbean)",
        "Saba (included in Dutch Caribbean (formerly Netherlands Antilles))",
        "Sint Eustatius (included Dutch Caribbean (formerly Netherlands Antilles))",
    ],
    BR: ["Brazil"],
    BS: ["Bahamas"],
    BT: ["Bhutan"],
    BV: ["Bouvet Island"],
    BW: ["Botswana"],
    BY: ["Belarus"],
    BZ: ["Belize"],
    CA: ["Canada"],
    CC: ["Cocos (Keeling) Island"],
    CD: [
        "Congo, Democratic Republic Of",
        "Zaire (included in Congo, Democratic Republic Of)",
    ],
    CF: ["Central African Republic"],
    CG: ["Congo (Republic)"],
    CH: ["Switzerland"],
    CI: ["Côte d'Ivoire"],
    CK: ["Cook Islands", "Rarotonga (included in Cook Islands)"],
    CL: ["Chile", "Easter Island (included in Chile)"],
    CM: ["Cameroon"],
    CN: [
        "China",
        "Inner Mongolia (included in China)",
        "Manchuria (included in China)",
        "Tibet (included in China)",
    ],
    CO: ["Colombia"],
    CR: ["Costa Rica"],
    CU: ["Cuba"],
    CV: ["Cape Verde"],
    CW: ["Curacao"],
    CX: ["Christmas Island"],
    CY: ["Cyprus"],
    CZ: ["Czech Republic"],
    DE: ["Germany"],
    DJ: ["Djibouti"],
    DK: ["Denmark"],
    DM: ["Dominica"],
    DO: ["Dominican Republic"],
    DZ: ["Algeria"],
    EC: ["Ecuador"],
    EE: ["Estonia"],
    EG: ["Egypt"],
    EH: ["Western Sahara"],
    ER: ["Eritrea"],
    ES: [
        "Spain",
        "Balearic Islands (included in Spain)",
        "Canary Islands (included in Spain)",
        "Spanish Territories of North Africa (included in Spain)",
    ],
    ET: ["Ethiopia"],
    FI: ["Finland"],
    FJ: ["Fiji"],
    FK: [
        "Falkland Islands",
        "British Antarctic Territory (included in Falkland Islands)",
        "Malvinas (included in Falkland Islands)",
        "South Georgia & South Sandwich Islands (included in Falkland Islands)",
        "South Orkney Islands (included in Falkland Islands)",
        "South Shetland Islands (included in Falkland Islands)",
    ],
    FM: [
        "Micronesia, Federal States Of",
        "Caroline Islands (included in Micronesia, Federal States of)",
        "Truk Island (included in Micronesia, Federal States Of)",
        "Yap Island (included in Micronesia, Federal States Of)",
    ],
    FO: ["Faroe Islands"],
    FR: ["France", "Corsica (included in France)"],
    GA: ["Gabon"],
    GB: [
        "United Kingdom (Great Britain)",
        "Channel Islands (included in United Kingdom (Great Britain))",
        "England (included in United Kingdom (Great Britain))",
        "Great Britain (included in United Kingdom (Great Britain))",
        "Northern Ireland (included in United Kingdom (Great Britain))",
        "Scotland (included in United Kingdom (Great Britain))",
        "Wales (included in United Kingdom (Great Britain))",
    ],
    GD: ["Grenada"],
    GE: ["Georgia"],
    GF: ["French Guiana"],
    GG: ["Guernsey"],
    GH: ["Ghana"],
    GI: ["Gibraltar"],
    GL: ["Greenland"],
    GM: ["Gambia"],
    GN: ["Guinea"],
    GP: ["Guadeloupe"],
    GQ: ["Equatorial Guinea"],
    GR: [
        "Greece",
        "Aegean Islands (included in Greece)",
        "Corfu (included in Greece)",
        "Crete (included in Greece)",
        "Dodecanese Island (included in Greece)",
    ],
    GT: ["Guatemala"],
    GU: ["Guam"],
    GW: ["Guinea-Bissau"],
    GY: ["Guyana"],
    HK: ["Hong Kong"],
    HM: ["Heard & McDonald Islands"],
    HN: ["Honduras"],
    HR: ["Croatia"],
    HT: ["Haiti"],
    HU: ["Hungary"],
    ID: [
        "Indonesia",
        "Billiton Island (included in Indonesia)",
        "Moluccas Islands (included in Indonesia)",
    ],
    IE: ["Ireland"],
    IL: ["Israel"],
    IM: ["Isle of Man"],
    IN: [
        "India",
        "Andaman Islands (included in India)",
        "Nicobar Island (included in India)",
    ],
    IQ: ["Iraq"],
    IR: ["Iran"],
    IS: ["Iceland"],
    IT: ["Italy", "Sicily (included in Italy)"],
    JE: ["Jersey"],
    JM: ["Jamaica"],
    JO: ["Jordan"],
    JP: ["Japan"],
    KE: ["Kenya"],
    KG: ["Kyrgyzstan"],
    KH: ["Cambodia"],
    KI: [
        "Kiribati",
        "Fanning Island (included in Kiribati)",
        "Gilbert Islands (included in Kiribati)",
        "Line Island (included in Kiribati)",
        "Ocean Island (included in Kiribati)",
        "Phoenix Island (included in Kiribati)",
        "Tarawa Island (included in Kiribati)",
        "Washington Island (included in Kiribati)",
    ],
    KM: ["Comoros"],
    KN: ["Saint Kitts and Nevis", "Nevis (included in Saint Kitts and Nevis)"],
    KP: ["Korea (Democratic People's Republic)"],
    KR: ["Korea (South)"],
    KW: ["Kuwait"],
    KY: ["Cayman Islands"],
    KZ: ["Kazakhstan"],
    LA: ["Lao (People's Democratic Republic)"],
    LB: ["Lebanon"],
    LC: ["Saint Lucia"],
    LI: ["Liechtenstein"],
    LK: ["Sri Lanka"],
    LR: ["Liberia"],
    LS: ["Lesotho"],
    LT: ["Lithuania"],
    LU: ["Luxembourg"],
    LV: ["Latvia"],
    LY: [
        "Libya",
        "Cyrenaica (included in Libya)",
        "Tripolitania (included in Libya)",
    ],
    MA: ["Morocco", "Ifni Territory (included in Morocco)"],
    MC: ["Monaco"],
    MD: ["Moldova"],
    ME: ["Montenegro"],
    MF: ["Saint Martin (French Part)"],
    MG: ["Madagascar"],
    MH: [
        "Marshall Islands",
        "Bikini Island (included in Marshall Islands)",
        "Enwetok and Kwajelein Islands (included in Marshall Islands)",
    ],
    MK: ["Macedonia"],
    ML: ["Mali"],
    MM: ["Myanmar", "Burma (included in Myanmar)"],
    MN: ["Mongolia"],
    MO: ["Macau"],
    MP: [
        "Northern Mariana Islands",
        "Mariana Islands (included in Northern Mariana Islands)",
    ],
    MQ: ["Martinique"],
    MR: ["Mauritania"],
    MS: ["Montserrat"],
    MT: ["Malta"],
    MU: ["Mauritius", "Rodriguez Island (included in Mauritius)"],
    MV: ["Maldives"],
    MW: ["Malawi"],
    MX: ["Mexico"],
    MY: ["Malaysia"],
    MZ: ["Mozambique"],
    NA: ["Namibia"],
    NC: [
        "New Caledonia",
        "Huon Islands (included in New Caledonia)",
        "Isle of Pines (included in New Caledonia)",
        "Loyalty Islands (included in New Caledonia)",
    ],
    NE: ["Niger"],
    NF: ["Norfolk Island"],
    NG: ["Nigeria"],
    NI: ["Nicaragua"],
    NL: ["Netherlands", "Holland (included in Netherlands)"],
    NO: ["Norway"],
    NP: ["Nepal"],
    NR: ["Nauru"],
    NU: ["Niue"],
    NZ: [
        "New Zealand",
        "Campbell Island (included in New Zealand)",
        "Chatham Island (included in New Zealand)",
        "Hervey Islands (included in New Zealand)",
        "Kermadec Islands (included in New Zealand)",
        "Ross Dependency (included in New Zealand)",
        "Suwarrow Island (included in New Zealand)",
    ],
    OM: ["Oman"],
    PA: ["Panama"],
    PE: ["Peru"],
    PF: [
        "French Polynesia",
        "Gambier Islands (included in French Polynesia)",
        "Marquesas Islands (included in French Polynesia)",
        "Society Islands (included in French Polynesia)",
        "Tahiti (included in French Polynesia)",
        "Touamotu Islands (included in French Polynesia)",
        "Tubuai Islands (included in French Polynesia)",
    ],
    PG: [
        "Papua New Guinea",
        "Admiralty Islands (included in Papua New Guinea)",
        "Manus Island (included in Papua New Guinea)",
        "New Britain (included in Papua New Guinea)",
        "New Ireland (included in Papua New Guinea)",
    ],
    PH: ["Philippines"],
    PK: ["Pakistan"],
    PL: ["Poland"],
    PM: ["Saint Pierre and Miquelon"],
    PN: [
        "Pitcairn",
        "Ducie Island (included in Pitcairn)",
        "Henderson Island (included in Pitcairn)",
        "Oeno Island (included in Pitcairn)",
    ],
    PR: ["Puerto Rico"],
    PS: ["West Bank and Gaza Strip"],
    PT: [
        "Portugal",
        "Azores (included in Portugal)",
        "Madeira (included in Portugal)",
    ],
    PW: ["Palau"],
    PY: ["Paraguay"],
    QA: ["Qatar"],
    RE: ["Réunion"],
    RO: ["Romania"],
    RS: [
        "Serbia",
        "Vojvodina (included in Serbia)",
        "Yugoslavia (included in Serbia)",
    ],
    RU: ["Russian Federation"],
    RW: ["Rwanda"],
    SA: ["Saudi Arabia"],
    SB: [
        "Solomon Islands",
        "Santas Cruz Island (included in Solomon Islands)",
        "Shortland Island (included in Solomon Islands)",
    ],
    SC: [
        "Seychelles",
        "British Indian Ocean Territory (included in Seychelles)",
        "Desroches (included in Seychelles)",
        "Farquhar Island (included in Seychelles)",
    ],
    SD: ["Sudan"],
    SE: ["Sweden"],
    SG: ["Singapore"],
    SH: ["Saint Helena", "Ascension (included in Saint Helena)"],
    SI: ["Slovenia"],
    SJ: ["Svalbard & Jan Mayen"],
    SK: ["Slovakia"],
    SL: ["Sierra Leone"],
    SM: ["San Marino"],
    SN: ["Senegal"],
    SO: ["Somalia"],
    SR: ["Suriname"],
    SS: ["South Sudan"],
    ST: [
        "Sao Tome and Principe",
        "Principe (included in Sao Tome and Principe)",
    ],
    SV: ["El Salvador"],
    SX: ["Sint Maarten (Dutch Part)"],
    SY: ["Syria"],
    SZ: ["Eswatini (formerly known as Swaziland)"],
    TA: ["Tristan da Cunha"],
    TC: ["Turks and Caicos Islands"],
    TD: ["Chad"],
    TF: ["French Southern Territories"],
    TG: ["Togo"],
    TH: ["Thailand"],
    TJ: ["Tajikistan"],
    TK: ["Tokelau", "Union Group (included in Tokelau)"],
    TL: [
        "Timor-Leste",
        "East Timor (included in Timor-Leste)",
        "Portuguese Timor (included in Timor-Leste)",
    ],
    TM: ["Turkmenistan"],
    TN: ["Tunisia"],
    TO: ["Tonga", "Friendly Islands (included in Tonga)"],
    TR: ["Turkey"],
    TT: ["Trinidad and Tobago"],
    TV: ["Tuvalu", "Ellice Island (included in Tuvalu)"],
    TW: ["Taiwan"],
    TZ: ["Tanzania"],
    UA: ["Ukraine"],
    UG: ["Uganda"],
    UM: [
        "U.S. Minor Outlying Islands",
        "Baker Island (included in U.S. Minor Outlying Islands)",
        "Howland Island (included in U.S. Minor Outlying Islands)",
        "Jarvis Island (included in U.S. Minor Outlying Island)",
        "Johnston Island (included in U.S. Minor Outlying Islands)",
        "Midway Island (included in U.S. Minor Outlying Island)",
        "Sand Island (included in U.S. Minor Outlying Islands)",
        "Savage Island (included in U.S. Minor Outlying Islands)",
        "Wake Island (included in U.S. Minor Outlying Islands)",
    ],
    US: [
        "United States of America",
        "Hawaii (included in United States of America)",
        "Navassa Island (included in United States of America)",
        "Trust Territory of Pacific (included in United States of America)",
    ],
    UY: ["Uruguay"],
    UZ: ["Uzbekistan"],
    VA: ["Holy See (Vatican)", "Vatican (included in Holy See (Vatican))"],
    VC: ["St Vincent and the Grenadines"],
    VE: ["Venezuela"],
    VG: [
        "British Virgin Islands",
        "Leeward Islands (included in British Virgin Islands)",
        "Tortola Island (included in British Virgin Islands)",
    ],
    VI: [
        "U.S. Virgin Islands",
        "St Croix (included in U.S. Virgin Islands)",
        "St John Island (included in U.S. Virgin Islands)",
        "St Thomas Island (included in U.S. Virgin Islands)",
    ],
    VN: ["Vietnam"],
    VU: ["Vanuatu", "Torres Island (included in Vanuatu)"],
    WF: [
        "Wallis and Futuna",
        "Alofi Islands (included in Wallis and Futana)",
        "Futuna Island (included in Wallis and Futuna)",
    ],
    WS: ["Samoa"],
    XZ: ["Kosovo", "Kosova (included in Kosovo)"],
    YE: ["Yemen", "Kamaran Islands (included in Yemen)"],
    YT: ["Mayotte"],
    ZA: ["South Africa"],
    ZM: ["Zambia"],
    ZW: ["Zimbabwe"],
};

// Correlates international destinations with 2-letter country codes
// ISO 3166 Alpha-2 Format: [Destination]: [2 letter Country Code]
const InternationalDestinations = Object.entries(Countries)
    .flatMap(([countryCode, destinations]) => {
        return destinations.map((destination) => ({
            [destination]: countryCode,
        }));
    })
    .reduce(
        (accumulator, destination) => ({ ...accumulator, ...destination }),
        {}
    );

export { InternationalDestinations };
