version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /webapp/timeline/k6_timeline.js
    volumes:
      - ../../webapp/timeline:/webapp/timeline
      - ../../inc:/inc
    environment: 
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
      - "HG_VUS=${HG_VUS}"
      - "HG_TYPE=${HG_TYPE}"
      - "HG_PASSWORD=${HG_PASSWORD}"

