apiVersion: v2
name: healthgateway
description: A Helm chart for Health Gateway
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redis-sentinel
    alias: redis
    version: 1.0.0
    condition: redis.enabled
    repository: "file://../redis-sentinel"
