apiVersion: v2
name: healthgateway
description: A Helm chart for Health Gateway
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: patroni
    version: 1.5.2
    condition: patroni.enabled
    repository: https://bcgov.github.io/sso-helm-charts
  - name: redis-sentinel
    alias: redis
    version: 1.0.0
    condition: redis.enabled
    repository: "file://../redis-sentinel"
