version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /webapp/options/k6_options.js
    volumes:
      - ../../webapp/options:/webapp/options
      - ../../inc:/inc
    environment:
      - "HG_URL=${HG_URL}"
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
      - "HG_VUS=${HG_VUS}"
      - "HG_TYPE=${HG_TYPE}"
      - "HG_PASSWORD=${HG_PASSWORD}"

