<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";

import { DateWrapper } from "@/models/dateWrapper";
import PatientData from "@/models/patientData";
import { SERVICE_IDENTIFIER } from "@/plugins/inversify";
import container from "@/plugins/inversify.config";
import { ILogger } from "@/services/interfaces";

@Component
export default class ReportHeaderComponent extends Vue {
    @Prop() private title!: string;
    @Prop() private startDate?: string;
    @Prop() private endDate?: string;
    @Prop() private patientData?: PatientData;

    private logger!: ILogger;

    private get currentDate() {
        return this.formatDateLong(new DateWrapper().toISO());
    }

    private created() {
        this.logger = container.get<ILogger>(SERVICE_IDENTIFIER.Logger);
    }

    private formatDateLong(date: string): string {
        return new DateWrapper(date).formatDateMed();
    }
}
</script>

<template>
    <div class="mb-1">
        <div class="header p-2 mb-4">
            <img
                class="d-block m-2"
                src="@/assets/images/gov/bcid-logo-rev-en.png"
                width="181"
                height="44"
                alt="BC Gov logo"
            />
        </div>
        <div>
            <h4 id="pageTitle" class="text-primary">
                {{ title }}
            </h4>
        </div>
        <div class="mr-1">
            <span class="small text-primary"
                >This record was generated by Provincial Health Gateway
                application. For any questions, please contact
                <strong>HealthGateway@gov.bc.ca</strong>
            </span>
        </div>
        <hr />
        <b-row align-h="end" class="py-1">
            <b-col class="text-muted small" cols="4">
                <strong>
                    Date Printed:
                    <span class="px-1">{{ currentDate }}</span>
                </strong>
            </b-col>
        </b-row>
        <b-row class="py-1 text-primary small">
            <b-col>
                <strong>Name:</strong>
                <span class="px-1"
                    >{{ patientData !== null ? patientData.firstname : "" }}
                    {{ patientData !== null ? patientData.lastname : "" }}</span
                >
            </b-col>
            <b-col>
                <strong>PHN:</strong>
                <span class="px-1">{{
                    patientData !== null ? patientData.personalhealthnumber : ""
                }}</span>
            </b-col>
            <b-col>
                <strong>Date of Birth:</strong>
                <span class="px-1">{{
                    patientData !== null ? patientData.birthdate : ""
                }}</span>
            </b-col>
        </b-row>
        <b-row v-if="startDate || endDate" class="pt-2 small">
            <b-col>
                <span class="text-muted">
                    Displaying records
                    {{ startDate ? `since ${formatDateLong(startDate)}` : "" }}
                    until
                    {{ endDate ? formatDateLong(endDate) : currentDate }}
                </span>
            </b-col>
        </b-row>
    </div>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/_variables.scss";

.text-primary {
    color: $primary !important;
}

.header {
    background-color: $primary;
    border-bottom: 2px solid $bcgold;
}

.soft-background {
    background-color: $soft_background;
}

.filterText {
    color: $soft_text;
    font-size: 0.8em;
    font-weight: normal;
}

hr {
    border-top: 2px solid $primary;
}
</style>
