<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import container from "@/plugins/inversify.config";
import { SERVICE_IDENTIFIER } from "@/plugins/inversify";
import { Action, Getter } from "vuex-class";
import { DateWrapper, StringISODate } from "@/models/dateWrapper";
import User from "@/models/user";
import { ILogger, IPatientService } from "@/services/interfaces";
import ErrorTranslator from "@/utility/errorTranslator";
import BannerError from "@/models/bannerError";

const userNamespace = "user";

@Component
export default class ReportHeaderComponent extends Vue {
    @Prop() private title!: Date;
    @Prop() private startDate?: Date;
    @Prop() private endDate?: Date;
    @Getter("user", { namespace: userNamespace })
    private user!: User;
    @Action("addError", { namespace: "errorBanner" })
    private addError!: (error: BannerError) => void;

    private logger!: ILogger;
    private firstName = "";
    private lastName = "";
    private phn = "";
    private dateOfBirth = "";

    private fetchPatientData() {
        const patientService: IPatientService = container.get<IPatientService>(
            SERVICE_IDENTIFIER.PatientService
        );

        patientService
            .getPatientData(this.user.hdid)
            .then((result) => {
                // Load patient data
                if (result) {
                    this.phn = result.resourcePayload.personalhealthnumber;
                    this.firstName = result.resourcePayload.firstname;
                    this.lastName = result.resourcePayload.lastname;
                    if (result.resourcePayload.birthdate != null) {
                        this.dateOfBirth = this.formatDate(
                            result.resourcePayload.birthdate
                        );
                    }
                }
            })
            .catch((err) => {
                this.logger.error(`Error fetching Patient Data: ${err}`);
                this.addError(
                    ErrorTranslator.toBannerError("Patient Data loading", err)
                );
            });
    }

    private formatDate(date: StringISODate): string {
        return new DateWrapper(date).format("yyyy-MM-dd");
    }

    private formatDateLong(date: Date): string {
        return new DateWrapper(date).toMediumDate();
    }

    private get currentDate() {
        return this.formatDateLong(new DateWrapper());
    }

    private mounted() {
        this.logger = container.get<ILogger>(SERVICE_IDENTIFIER.Logger);
        this.fetchPatientData();
    }
}
</script>

<template>
    <div>
        <div id="pageTitle">
            <h3 id="subject">
                {{ title }}
            </h3>
        </div>
        <div id="disclaimer" class="mr-1">
            <span>Disclaimer:</span> This record was generated by Provincial
            Health Gateway application. For any questions, please contact
            HealthGateway@gov.bc.ca
        </div>
        <hr />
        <b-row align-h="end">
            <b-col class="datePrintedCol" cols="4">
                <label>Date Printed:</label>&nbsp;
                <span>{{ currentDate }}&nbsp;</span>
            </b-col>
        </b-row>
        <b-row class="pt-2">
            <b-col>
                <label>Name:&nbsp;</label>
                <span class="px-1">{{ firstName }} {{ lastName }}</span>
            </b-col>
            <b-col>
                <label>PHN:</label>
                <span class="px-1">{{ phn }}</span>
            </b-col>
            <b-col>
                <label>Date of Birth:</label>
                <span class="px-1">{{ dateOfBirth }}</span>
            </b-col>
        </b-row>
        <b-row v-if="startDate || endDate" class="pt-2">
            <b-col>
                <span class="filterText">
                    Displaying records
                    {{ startDate ? `since ${formatDateLong(startDate)}` : "" }}
                    until
                    {{ endDate ? formatDateLong(endDate) : currentDate }}
                </span>
            </b-col>
        </b-row>
    </div>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/_variables.scss";

#pageTitle,
#disclaimer,
label,
span {
    color: $primary;
}

#disclaimer {
    font-size: 0.7em;
    span {
        font-weight: bold !important;
    }
}

.datePrintedCol {
    label,
    span {
        color: $soft_text !important;
    }
}

.filterText {
    color: $soft_text;
    font-size: 0.8em;
    font-weight: normal;
}

#disclaimer,
span {
    font-weight: bold;
}

label,
#disclaimer {
    font-size: 0.9em;
}
hr {
    border-top: 2px solid $primary;
}
</style>
