<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";

import { DateWrapper } from "@/models/dateWrapper";
import PatientData from "@/models/patientData";
import { SERVICE_IDENTIFIER } from "@/plugins/inversify";
import container from "@/plugins/inversify.config";
import { ILogger } from "@/services/interfaces";

@Component
export default class ReportHeaderComponent extends Vue {
    @Prop() private title!: string;
    @Prop() private startDate?: string;
    @Prop() private endDate?: string;
    @Prop() private patientData?: PatientData;

    private logger!: ILogger;

    private formatDateLong(date: string): string {
        return new DateWrapper(date).toMediumDate();
    }

    private get currentDate() {
        return this.formatDateLong(new DateWrapper().toISO());
    }

    private mounted() {
        this.logger = container.get<ILogger>(SERVICE_IDENTIFIER.Logger);
    }
}
</script>

<template>
    <div>
        <div id="pageTitle">
            <h3 id="subject">
                {{ title }}
            </h3>
        </div>
        <div id="disclaimer" class="mr-1">
            This record was generated by Provincial Health Gateway application.
            For any questions, please contact HealthGateway@gov.bc.ca
        </div>
        <hr />
        <b-row align-h="end">
            <b-col class="datePrintedCol" cols="4">
                <label>Date Printed:</label>
                <span class="px-1">{{ currentDate }}</span>
            </b-col>
        </b-row>
        <b-row class="pt-2">
            <b-col>
                <label>Name:</label>
                <span class="px-1"
                    >{{ patientData !== null ? patientData.firstname : "" }}
                    {{ patientData !== null ? patientData.lastname : "" }}</span
                >
            </b-col>
            <b-col>
                <label>PHN:</label>
                <span class="px-1">{{
                    patientData !== null ? patientData.personalhealthnumber : ""
                }}</span>
            </b-col>
            <b-col>
                <label>Date of Birth:</label>
                <span class="px-1">{{
                    patientData !== null ? patientData.birthdate : ""
                }}</span>
            </b-col>
        </b-row>
        <b-row v-if="startDate || endDate" class="pt-2">
            <b-col>
                <span class="filterText">
                    Displaying records
                    {{ startDate ? `since ${formatDateLong(startDate)}` : "" }}
                    until
                    {{ endDate ? formatDateLong(endDate) : currentDate }}
                </span>
            </b-col>
        </b-row>
    </div>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/_variables.scss";

#pageTitle,
#disclaimer,
label,
span {
    color: $primary;
}

#disclaimer {
    font-size: 0.7em;
    span {
        font-weight: bold !important;
    }
}

.datePrintedCol {
    label,
    span {
        color: $soft_text !important;
    }
}

.filterText {
    color: $soft_text;
    font-size: 0.8em;
    font-weight: normal;
}

#disclaimer,
span {
    font-weight: bold;
}

label,
#disclaimer {
    font-size: 0.9em;
}
hr {
    border-top: 2px solid $primary;
}
</style>
