<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import MedicationStatementHistory from "@/models/medicationStatementHistory";
import moment from "moment";

@Component
export default class MedicationHistoryReportComponent extends Vue {
    private notFoundText: string = "Not Found";
    @Prop() private medicationStatementHistory!: MedicationStatementHistory[];
    @Prop() private name!: string;

    private get currentDate() {
        return moment(new Date()).format("ll");
    }

    private get isEmpty() {
        return this.medicationStatementHistory.length == 0;
    }

    private formatDate(date: Date): string {
        return moment(date).format("yyyy-MM-DD");
    }
}
</script>

<template>
    <section class="pdf-item">
        <div id="pageTitle">
            <h3 id="subject">Health Gateway Medication History Report</h3>
        </div>
        <div id="disclaimer" class="mr-1">
            Disclaimer: This report was generated by the Health Gateway and not
            serve as the legal record of dispensed medication history for this
            individual.
        </div>
        <hr class="mb-0" />
        <b-row class="pt-2">
            <b-col>
                <label>Name:</label> <span>{{ name }}</span>
            </b-col>
        </b-row>
        <b-row class="pt-2">
            <b-col>
                <label>Date Reported:</label> <span>{{ currentDate }}</span>
            </b-col>
        </b-row>

        <b-row v-if="isEmpty" class="mt-2">
            <b-col>No records found.</b-col>
        </b-row>
        <b-row v-else class="py-3 mt-4 header">
            <b-col class="col-1">Date</b-col>
            <b-col class="col-1">DIN/PIN</b-col>
            <b-col class="col-2">Brand</b-col>
            <b-col class="col-2">Generic</b-col>
            <b-col class="col-1">Practitioner</b-col>
            <b-col class="col-1">Quantity</b-col>
            <b-col class="col-1">Strength</b-col>
            <b-col class="col-1">Form</b-col>
            <b-col class="col-1">Manufacturer</b-col>
        </b-row>
        <b-row
            v-for="item in medicationStatementHistory"
            :key="item.prescriptionIdentifier + item.dispensedDate"
            class="item py-1"
        >
            <b-col class="col-1 my-auto text-nowrap">
                {{ formatDate(item.dispensedDate) }}
            </b-col>
            <b-col class="col-1 my-auto">
                {{ item.medicationSummary.din }}
            </b-col>
            <b-col class="col-2 my-auto">
                {{ item.medicationSummary.brandName }}
            </b-col>
            <b-col class="col-2 my-auto">
                {{ item.medicationSummary.genericName || notFoundText }}
            </b-col>
            <b-col class="col-1 my-auto">{{ item.practitionerSurname }}</b-col>
            <b-col class="col-1 my-auto">
                {{ item.medicationSummary.quantity }}
            </b-col>
            <b-col class="col-1 my-auto">
                {{
                    item.medicationSummary.strength +
                        item.medicationSummary.strengthUnit || notFoundText
                }}
            </b-col>
            <b-col class="col-1 my-auto">
                {{ item.medicationSummary.form || notFoundText }}
            </b-col>
            <b-col class="col-1 my-auto">
                {{ item.medicationSummary.manufacturer || notFoundText }}
            </b-col>
        </b-row>
    </section>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/_variables.scss";

#pageTitle,
#disclaimer,
label,
span {
    color: $primary;
}

#disclaimer {
    font-size: 0.7em;
}

#disclaimer,
span {
    font-weight: bold;
}

label,
#disclaimer {
    font-size: 0.9em;
}
hr {
    border-top: 2px solid $primary;
}

.header {
    background-color: $soft_background;
    font-weight: bold;
    font-size: 0.7em;
    text-align: center;
}

.item {
    font-size: 0.6em;
    border-bottom: solid 1px $soft_background;
    page-break-inside: avoid;
    text-align: center;
}

.item:nth-child(odd) {
    background-color: $medium_background;
}
.item:nth-child(even) {
    background-color: $soft_background;
}
</style>
