<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import moment from "moment";
import Encounter from "@/models/encounter";

@Component
export default class MSPVisitsReportComponent extends Vue {
    private notFoundText = "Not Found";
    @Prop() private records!: Encounter[];
    @Prop() private name!: string;

    private get currentDate() {
        return moment(new Date()).format("ll");
    }

    private get isEmpty() {
        return this.records.length == 0;
    }

    private formatDate(date: Date): string {
        return moment(date).format("yyyy-MM-DD");
    }
}
</script>

<template>
    <section class="pdf-item">
        <div id="pageTitle">
            <h3 id="subject">Health Gateway MSP Visits Report</h3>
        </div>
        <div id="disclaimer" class="mr-1">
            Disclaimer: This report was generated by the Health Gateway and not
            serve as the legal record of MSP Visits for this individual.
        </div>
        <hr class="mb-0" />
        <b-row class="pt-2">
            <b-col>
                <label>Name:</label> <span>{{ name }}</span>
            </b-col>
        </b-row>
        <b-row class="pt-2">
            <b-col>
                <label>Date Reported:</label> <span>{{ currentDate }}</span>
            </b-col>
        </b-row>

        <b-row v-if="isEmpty" class="mt-2">
            <b-col>No records found.</b-col>
        </b-row>
        <b-row v-else class="py-3 mt-4 header">
            <b-col class="col">Date</b-col>
            <b-col class="col">Provider Name</b-col>
            <b-col class="col">Specialty Description</b-col>
            <b-col class="col">Clinic Location</b-col>
        </b-row>
        <b-row v-for="item in records" :key="item.id" class="item py-1">
            <b-col class="col my-auto text-nowrap">
                {{ formatDate(item.encounterDate) }}
            </b-col>
            <b-col class="col my-auto">
                {{ item.practitionerName }}
            </b-col>
            <b-col class="col my-auto">
                {{ item.specialtyDescription }}
            </b-col>
            <b-col class="col my-auto">
                <p>{{ item.clinic.name }}</p>
                <p>{{ item.clinic.address }}</p>
            </b-col>
        </b-row>
    </section>
</template>

<style lang="scss" scoped>
@import "@/assets/scss/_variables.scss";

#pageTitle,
#disclaimer,
label,
span {
    color: $primary;
}

#disclaimer {
    font-size: 0.7em;
}

#disclaimer,
span {
    font-weight: bold;
}

label,
#disclaimer {
    font-size: 0.9em;
}
hr {
    border-top: 2px solid $primary;
}

.header {
    background-color: $soft_background;
    font-weight: bold;
    font-size: 0.7em;
    text-align: center;
}

.item {
    font-size: 0.6em;
    border-bottom: solid 1px $soft_background;
    page-break-inside: avoid;
    text-align: center;
}

.item:nth-child(odd) {
    background-color: $medium_background;
}
.item:nth-child(even) {
    background-color: $soft_background;
}
</style>
