name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Database

trigger: none

pool:
  name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Database
    DotNetTests: true
    NPMInstall: false
    NPMTests: false
    Library: true
