name: 1.0.0$(Rev:.r) #Build number

trigger:
  batch: "true"
  paths:
    include:
      - Tools/AzureAgent

pool:
  name: "HealthGateway"
  vmImage: "ubuntu-latest"

steps:
- task: Docker@2
  displayName: Build Azure Agent
  inputs:
    command: 'buildAndPush'
    repository: $(DockerRepo)/azure-agent
    buildContext: '$(Build.SourcesDirectory)/Tools/AzureAgent'
    dockerfile: '$(Build.SourcesDirectory)/Tools/AzureAgent/docker/Dockerfile'
    tags: |
      latest
