apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinicaldocument.fullname" . }}
  labels:
    {{- include "clinicaldocument.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.Application.Port }}
      protocol: TCP
  selector:
    {{- include "clinicaldocument.selectorLabels" . | nindent 4 }}
    deploymentconfig: {{ include "clinicaldocument.fullname" . }}
