@startuml PHSA_CDC_Laboratory_Flow
autonumber
actor Citizen
Citizen -> HealthGateway_WebClient : Login
HealthGateway_WebClient <-> KeyCloak_AuthServer : OIDC Authentication Request
Citizen <-> BCSC_IDIM_Services : External IdP; BCSC login flow at id.gov.bc.ca
BCSC_IDIM_Services -> KeyCloak_AuthServer : Redirect back after successful BCSC login
HealthGateway_WebClient <- KeyCloak_AuthServer : Authentication Successful, Grant JWT
HealthGateway_WebClient -> HealthGateway_Laboratory_Controller : Fetch COVID Results
HealthGateway_Laboratory_Controller -> PHSA_CDC_Laboratory_Service : /api/v1/LabReports Fetch All COVID Results (JWT, HDID)
PHSA_CDC_Laboratory_Service -> KeyCloak_AuthServer : Verify Access Token by fetching public key (JWT)
PHSA_CDC_Laboratory_Service <-> PHSA_CDC_Laboratory_Service : Verify Scope in JWT is correct
PHSA_CDC_Laboratory_Service <-> PHSA_CDC_Laboratory_Service :  Resolve HDID to PHN using internal HCIM access
HealthGateway_WebClient <- PHSA_CDC_Laboratory_Service :  Return LabReports for this user
Citizen -> HealthGateway_WebClient : Select to View LabReport Document (a PDF)
HealthGateway_WebClient -> HealthGateway_Laboratory_Controller : initiate fetch for Lab Report document
HealthGateway_Laboratory_Controller -> PHSA_CDC_Laboratory_Service:  /api/v1/{id}/LabReportDocument Fetch All COVID Report Doc (JWT, HDID)
PHSA_CDC_Laboratory_Service -> KeyCloak_AuthServer : Verify Access Token by fetching public key (JWT)
PHSA_CDC_Laboratory_Service <-> PHSA_CDC_Laboratory_Service : Verify Scope in JWT is correct
PHSA_CDC_Laboratory_Service <-> PHSA_CDC_Laboratory_Service : Resolve HDID to PHN using internal HCIM access
HealthGateway_WebClient <- PHSA_CDC_Laboratory_Service : Return Lab report document (PDF) for this user
Citizen -> HealthGateway_WebClient : View and/or Download PDF Document
@enduml
