CREATE ROLE hglocal WITH
  LOGIN
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  PASSWORD 'SCRAM-SHA-256$4096:egq5ClJecfPlUdeeJ9FnUw==$EoDP8QByj46KZtM+KeA1/Wfg+bycwe3+GWqUsfUdSpU=:5icZi5mEKeLG/UK80qKuUKYN1cCmH/DqJ076GUwG9PI=';

CREATE DATABASE hglocal WITH 
  OWNER = hglocal
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8'
  CONNECTION LIMIT = -1
  TEMPLATE template0;

GRANT hglocal to postgres;

\c hglocal
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";