CREATE ROLE hglocal WITH
  LOGIN
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  PASSWORD 'md5126dc4528b42dad68fd970be654bcfe4';

CREATE DATABASE hglocal WITH 
  OWNER = hglocal
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE = 'en_US.UTF-8'
  CONNECTION LIMIT = -1
  TEMPLATE template0;

GRANT hglocal to postgres;

\c hglocal
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";