{{- range $env, $vars := .Values.azureagent.envs -}}
{{- $name := print $env "-azureagent"  -}}
{{- $token := $.Values.token | required "values.token is required" -}}
{{- $dr := ($.Values.dr | required "values.dr is required") | ternary "DR" "" -}}
{{- $azurePoolPrefix := print (($.Values.azureagent).poolPrefix | required "azureagent.poolPrefix is required") $dr -}}
{{- $azureDevopsUrl := ($.Values.azureagent).devopsUrl | required "azureagent.devopsUrl is required" -}}
{{- $imageTag := ($vars).imageTag | default $env -}}
{{- $vaultEngine := ($vars).vaultEngine | default $.Values.vault.engine -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secrets
  namespace: {{ $.Values.licensePlate }}-{{  $env  }}
type: Opaque
data:
  AZP_TOKEN: {{ $token | toString | b64enc }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}-vault-rb
  namespace: {{ $.Values.licensePlate }}-{{  $env  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ $.Values.licensePlate }}-vault
  namespace: {{ $.Values.licensePlate }}-{{  $env  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vaull-pull-{{ $env }}-rb
  namespace: {{ $.Values.licensePlate }}-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: {{ $.Values.licensePlate }}-vault
  namespace: {{ $.Values.licensePlate }}-{{  $env  }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.licensePlate }}-{{ $env }}
spec:
  replicas: {{ ($vars).replicas | default 1 }}
  podManagementPolicy: Parallel
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: {{ $name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  {{ $name }}
      annotations:
        image.openshift.io/triggers: >-
          [{"from": {"kind": "ImageStreamTag","name": {{ $.Values.azureagent.baseImage | base }}:{{ $imageTag }},"namespace": {{ $.Values.licensePlate }}-tools},"fieldPath": "spec.template.spec.containers[?(@.name==\"{{ $name }}\")].image","paused": "false"}]
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-token: 'true'
        vault.hashicorp.com/agent-inject-auto-auth: 'true'
        vault.hashicorp.com/agent-cache-use-auto-auth-token: 'true'
        vault.hashicorp.com/agent-pre-populate-only: 'false'
        vault.hashicorp.com/auth-path: {{ $.Values.vault.authPath }}{{ lower $dr }}
        vault.hashicorp.com/namespace: {{ $.Values.vault.namespace }}
        vault.hashicorp.com/role: {{ $.Values.licensePlate }}-{{ $vaultEngine }}
    spec:
      serviceAccountName: {{ $.Values.licensePlate }}-vault
      containers:
        - name:  {{ $name }}
          image: {{ $.Values.azureagent.baseImage }}:{{ $imageTag }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ print $name "-secrets" }}
          env:
            - name: AZP_URL
              value: {{ $azureDevopsUrl }}
            - name: AZP_POOL
              value: {{ $azurePoolPrefix }}{{ title $env }}
          resources:
            limits:
              cpu: {{ (($vars).resources).cpulimit | default "250m" }}
              memory: {{ (($vars).resources).memlimit | default "1Gi" }}
            requests:
              cpu: {{ (($vars).resources).cpurequest | default "50m" }}
              memory: {{ (($vars).resources).memrequest | default "256Mi" }}
          volumeMounts:
            - mountPath: /opt/az/_work
              name: ephemeral-work
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: ephemeral-work
          emptyDir: {}
---
{{ end -}}
