version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /services/medication/k6_medication.js
    volumes:
      - ../../services/medication:/services/medication
      - ../../inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_VUS=${HG_VUS}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
