version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run /webapp_api/comments/k6_comments.js
    volumes:
      - ../../../src/webapp_api/comments:/webapp_api/comments
      - ../../../src/inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_VUS=${HG_VUS}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
