name: 1.1.0$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Immunization
        - Apps/Common
        - Apps/Database

resources:
 pipelines:
   - pipeline: Common
     source: Common
     trigger:
       branches:
       - dev
       
trigger:
    batch: "true"
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Immunization

pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Immunization
    DotNetTests: true
    FunctionalTests: false
    NPMInstall: false
    NPMTests: false

