name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Laboratory
    # - Apps/Common
    # - Apps/Database

trigger: none

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Laboratory
    DotNetTests: true
    NPMInstall: false
    NPMTests: false
