name: PR$(Rev:.r) #Build number

#Build variables
variables:
  App.Home: $(Build.SourcesDirectory)/Apps/Laboratory
  App.Name: laboratory
  App.UnitTests: $(App.Home)/test/unit
  App.FunctionalTests: $(App.Home)/test/functional

pool:
  name: "HealthGateway"

trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Laboratory
      - Apps/Common
      - Apps/Database

steps:
  - task: DotNetCoreCLI@2
    displayName: Run dotnet Tests
    inputs:
      command: "test"
      projects: "$(App.UnitTests)/LaboratoryTests.csproj"
      testRunTitle: "Labratory Service Tests"

  - task: DotNetCoreCLI@2
    displayName: "Publish dotnet Code"
    inputs:
      modifyOutputPath: false
      command: "publish"
      publishWebProjects: false
      projects: "$(App.Home)/src"
      arguments: "-o $(Build.BinariesDirectory)"
      zipAfterPublish: false
