name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Mock

trigger: none

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Mock
    DotNetTests: false
    NPMInstall: false
    NPMTests: false
