export enum ClientModule {
    Immunization = "Immunization",
    Medication = "Medication",
    MedicationRequest = "MedicationRequest",
    Laboratory = "Laboratory",
    Encounter = "Encounter",
    Comment = "Comment",
    CovidLabResults = "CovidLabResults",
    Dependent = "Dependent",
    Note = "Note",
    VaccinationStatus = "VaccinationStatus",
    VaccinationStatusPdf = "VaccinationStatusPdf",
    VaccinationExportPdf = "VaccinationExportPdf",
    FederalCardButton = "FederalCardButton",
    PublicLaboratoryResult = "PublicLaboratoryResult",
    AllLaboratory = "AllLaboratory",
    PcrTest = "PcrTest",
}
