export enum Path {
    Root = "/",
    AcceptTermsOfService = "/acceptTermsOfService",
    Busy = "/busy",
    Covid19 = "/covid19",
    Dependents = "/dependents",
    Home = "/home",
    IdirLoggedIn = "/idirLoggedIn",
    Login = "/login",
    LoginCallback = "/loginCallback",
    Logout = "/logout",
    LogoutComplete = "/logoutComplete",
    NotFound = "/not-found",
    PatientRetrievalError = "/patientRetrievalError",
    PcrTestKitRegistration = "/pcrtest",
    Profile = "/profile",
    Registration = "/registration",
    Reports = "/reports",
    Services = "/services",
    TermsOfService = "/termsOfService",
    Timeline = "/timeline",
    Unauthorized = "/unauthorized",
    VaccineCard = "/vaccinecard",
    ValidateEmail = "/validateEmail",
}
