export const enum ServiceCode {
    DataBase = "DB",
    ClientRegistries = "CR",
    ODR = "ODR",
    HealthGatewayUser = "HGU",
    Medication = "MED",
    SpecialAuthority = "SPA",
    Laboratory = "LAB",
    Immunization = "IMZ",
    Encounter = "ENC",
    HospitalVisit = "HOS",
    Patient = "PAT",
    PHSA = "PHSA",
    Report = "REP",
    ClinicalDocument = "CDO",
    Ticket = "TCK",
}
