name: 1.0.0$(Rev:.r) #Build number

pr: none

resources:
  pipelines:
  - pipeline: Common
    source: Common
    trigger:
      branches:
        include:
        - dev

trigger:
  batch: "true"
  branches:
    include:
    - dev
  paths:
    include:
    - Apps/ClinicalDocument

extends:
  template: /Build/hg.yaml
  parameters:
    Application: ClinicalDocument
    DotNetTests: true
    NPMInstall: false
    