name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
  batch: true
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Offline

pool:
  vmImage: "ubuntu-20.04"

variables:
  - group: Secrets
  - name: App.Name
    value: Offline
  - name: Image.Name
    value: $[lower(variables['App.Name'])]
  - name: App.Home
    value: $(Build.SourcesDirectory)/Apps/$(App.Name)

steps:
  - task: Docker@2
    displayName: "Building Image for $(App.Name) and pushing to Docker Hub"
    inputs:
      containerRegistry: "docker-health"
      repository: $(DockerRepo)/$(Image.Name)
      Dockerfile: "$(App.Home)/Dockerfile"
      buildContext: "$(App.Home)"
      tags: "$(Build.BuildNumber)"
