version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run /webapp_api/configuration/k6_configuration.js
    volumes:
      - ../../webapp_api/configuration:/webapp_api/configuration
      - ../../inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_VUS=${HG_VUS}"
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
