name: PR$(Rev:.r) #Build number

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/CommonUi

trigger: none

extends:
  template: /Build/hg.yaml
  parameters:
    Application: CommonUi
    DotNetTests: true
    NPMInstall: false
    NPMTests: false
    Library: true
