name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
  batch: true
  branches:
    include:
      - dev
  paths:
    include:
      - Tools/Pipelines

jobs:
  - job: "Package_Scripts"
    displayName: "Package Scripts"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: CopyFiles@2
        displayName: "Package Deployment Scripts"
        inputs:
          SourceFolder: Tools/Pipelines
          Contents: |
            pipelines/**
            scripts/**
          TargetFolder: "$(Build.ArtifactStagingDirectory)"
      - task: PublishPipelineArtifact@1
        displayName: "Publish Deployment Artifacts"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)"
          artifact: drop
