//-------------------------------------------------------------------------
// Copyright © 2019 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-------------------------------------------------------------------------
// <auto-generated />
#pragma warning disable CS1591
using System;
using HealthGateway.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HealthGateway.Database.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20200218200745_UpdateUserFeedbackReviewed")]
    partial class UpdateUserFeedbackReviewed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gateway")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("Relational:Sequence:.gateway.trace_seq", "'gateway.trace_seq', '', '1', '1', '1', '999999', 'Int64', 'True'");

            modelBuilder.Entity("HealthGateway.Database.Models.ActiveIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ActiveIngredientId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveIngredientCode")
                        .HasColumnType("integer");

                    b.Property<string>("Base")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DosageUnit")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("DosageUnitFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("DosageValue")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ingredient")
                        .HasColumnType("character varying(240)")
                        .HasMaxLength(240);

                    b.Property<string>("IngredientFrench")
                        .HasColumnType("character varying(400)")
                        .HasMaxLength(400);

                    b.Property<string>("IngredientSuppliedInd")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Notes")
                        .HasColumnType("character varying(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Strength")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("StrengthType")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("StrengthTypeFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("StrengthUnit")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("StrengthUnitFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("ActiveIngredient");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AuditEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationSubject")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("AuditEventDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Trace")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<long?>("TransactionDuration")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionName")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("TransactionResultCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("TransactionVersion")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationType");

                    b.HasIndex("TransactionResultCode");

                    b.ToTable("AuditEvent");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.AuditTransactionResultCode", b =>
                {
                    b.Property<string>("ResultCode")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("ResultCode");

                    b.ToTable("AuditTransactionResultCode");

                    b.HasData(
                        new
                        {
                            ResultCode = "Ok",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Success",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ResultCode = "Fail",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Failure",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ResultCode = "NotAuth",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unauthorized",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ResultCode = "Err",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "System Error",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HealthGateway.Database.Models.BetaRequest", b =>
                {
                    b.Property<string>("HdId")
                        .HasColumnName("BetaRequestId")
                        .HasColumnType("character varying(52)")
                        .HasMaxLength(52);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("character varying(254)")
                        .HasMaxLength(254);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("HdId");

                    b.ToTable("BetaRequest");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressBillingFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("AddressMailingFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("AddressNotificationFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("AddressOther")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("CityName")
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<int>("CompanyCode")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("CompanyType")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Country")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("CountryFrench")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManufacturerCode")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("PostOfficeBox")
                        .HasColumnType("character varying(15)")
                        .HasMaxLength(15);

                    b.Property<string>("PostalCode")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Province")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("ProvinceFrench")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("StreetName")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("SuiteNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("Company");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.DrugProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessionNumber")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("AiGroupNumber")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("BrandNameFrench")
                        .HasColumnType("character varying(300)")
                        .HasMaxLength(300);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descriptor")
                        .HasColumnType("character varying(150)")
                        .HasMaxLength(150);

                    b.Property<string>("DescriptorFrench")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("DrugClass")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("DrugClassFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("DrugCode")
                        .IsRequired()
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<string>("DrugIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("character varying(29)")
                        .HasMaxLength(29);

                    b.Property<Guid>("FileDownloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NumberOfAis")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PediatricFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("ProductCategorization")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("FileDownloadId");

                    b.ToTable("DrugProduct");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmailId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailStatusCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("FormatCode")
                        .IsRequired()
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("character varying(254)")
                        .HasMaxLength(254);

                    b.Property<DateTime?>("LastRetryDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SmtpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("character varying(254)")
                        .HasMaxLength(254);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("EmailStatusCode");

                    b.HasIndex("FormatCode");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailFormatCode", b =>
                {
                    b.Property<string>("FormatCode")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("FormatCode");

                    b.ToTable("EmailFormatCode");

                    b.HasData(
                        new
                        {
                            FormatCode = "Text",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            FormatCode = "HTML",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmailInviteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HdId")
                        .HasColumnType("character varying(52)")
                        .HasMaxLength(52);

                    b.Property<Guid>("InviteKey")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Validated")
                        .HasColumnType("boolean");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("EmailId");

                    b.ToTable("EmailInvite");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailStatusCode", b =>
                {
                    b.Property<string>("StatusCode")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("StatusCode");

                    b.ToTable("EmailStatusCode");

                    b.HasData(
                        new
                        {
                            StatusCode = "New",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A newly created email",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            StatusCode = "Pending",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An email pending batch pickup",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            StatusCode = "Processed",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An email that has been sent",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            StatusCode = "Error",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An Email that will not be sent",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EmailTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FormatCode")
                        .IsRequired()
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("character varying(254)")
                        .HasMaxLength(254);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("FormatCode");

                    b.ToTable("EmailTemplate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("040c2ec3-d6c0-4199-9e4b-ebe6da48d52a"),
                            Body = @"<!doctype html>
<html lang=""en"">
<head></head>
<body style = ""margin:0"">
    <table cellspacing=""0"" align=""left"" width=""100%"" style=""margin:0;color:#707070;font-family:Helvetica;font-size:12px;"">
        <tr style = ""background:#003366;"">
            <th width=""45"" ></th>
            <th width=""350"" align=""left"" style=""text-align:left;"">
                <div role=""img"" aria - label=""Health Gateway Logo"">
                    <img src=""${ActivationHost}/Logo.png"" alt=""Health Gateway Logo""/>
                </div>
            </th>
            <th width=""""></th>
        </tr>
        <tr>
            <td colspan=""3"" height=""20""></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <h1 style = ""font-size:18px;"">Almost there!</h1>
                <p>We've received a request to register your email address for a Ministry of Health Gateway account.</p>
                <p>To activate your account, please verify your email by clicking the link:</p>
                <a style = ""color:#1292c5;font-weight:600;"" href = ""${ActivationHost}/ValidateEmail/${InviteKey}""> Health Gateway account verification </a>
            </td>
            <td></td>
        </tr>
    </table>
</body>
</html>",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormatCode = "HTML",
                            From = "HG_Donotreply@gov.bc.ca",
                            Name = "Registration",
                            Priority = 10,
                            Subject = "Health Gateway Email Verification ${Environment}",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("896f8f2e-3bed-400b-acaf-51dd6082b4bd"),
                            Body = @"<!doctype html>
    <html lang=""en"">
    <head></head>
    <body style=""margin:0"">
    <table cellspacing=""0"" align=""left"" width=""100%"" style=""margin:0;color:#707070;font-family:Helvetica;font-size:12px;"">
        <tr style=""background:#036;"">
            <th width=""45""></th>
            <th width=""350"" align=""left"" style=""text-align:left;"">
                <div role=""img"" aria-label=""Health Gateway Logo"">
                    <img src=""${host}/Logo.png"" alt=""Health Gateway Logo""/>
                </div>
            </th>
            <th width=""""></th>
        </tr>
        <tr>
            <td colspan=""3"" height=""20""></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <h1 style=""font-size:18px;"">Good day,</h1>
                <p>You are receiving this email as a Health Gateway patient partner. We welcome your feedback and suggestions as one of the first users of the application.</p>
                <p>Please click on the link below which will take you to your registration for the Health Gateway service. This registration link is valid for your one-time use only. We kindly ask that you do not share your link with anyone else.</p>
                <a style = ""font-weight:600;"" href=""${host}/registrationInfo?inviteKey=${inviteKey}&email=${emailTo}"">Register Now</a>
                <p>If you have any questions about the registration process, including signing up to use your BC Services Card for authentication, please contact Nino Samson at nino.samson@gov.bc.ca.</p>
            </td>
            <td></td>
        </tr>
    </table>
</body>
</html>",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormatCode = "HTML",
                            From = "HG_Donotreply@gov.bc.ca",
                            Name = "Invite",
                            Priority = 1,
                            Subject = "Health Gateway Private Invitation",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            Id = new Guid("2ab5d4aa-c4c9-4324-a753-cde4e21e7612"),
                            Body = @"<!doctype html>
    <html lang=""en"">
    <head></head>
    <body style=""margin:0"">
    <table cellspacing=""0"" align=""left"" width=""100%"" style=""margin:0;color:#707070;font-family:Helvetica;font-size:12px;"">
        <tr style=""background:#036;"">
            <th width=""45""></th>
            <th width=""350"" align=""left"" style=""text-align:left;"">
                <div role=""img"" aria-label=""Health Gateway Logo"">
                    <img src=""${host}/Logo.png"" alt=""Health Gateway Logo""/>
                </div>
            </th>
            <th width=""""></th>
        </tr>
        <tr>
            <td colspan=""3"" height=""20""></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <h1 style=""font-size:18px;"">Good day,</h1>
                <p>Thank you for joining the wait list to be an early user of the Health Gateway.</p>
                <p>You will receive an email in the near future with a registration link.</p>
            </td>
            <td></td>
        </tr>
    </table>
</body>
</html>",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FormatCode = "HTML",
                            From = "HG_Donotreply@gov.bc.ca",
                            Name = "BetaConfirmation",
                            Priority = 1,
                            Subject = "Health Gateway Waitlist Confirmation",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HealthGateway.Database.Models.FileDownload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FileDownloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("character varying(44)")
                        .HasMaxLength(44);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(35)")
                        .HasMaxLength(35);

                    b.Property<string>("ProgramCode")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("ProgramCode")
                        .IsUnique();

                    b.ToTable("FileDownload");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FormId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PharmaceuticalForm")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<int>("PharmaceuticalFormCode")
                        .HasColumnType("integer");

                    b.Property<string>("PharmaceuticalFormFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("Form");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Packaging", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PackagingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageSize")
                        .HasColumnType("character varying(5)")
                        .HasMaxLength(5);

                    b.Property<string>("PackageSizeUnit")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PackageSizeUnitFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PackageType")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PackageTypeFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("ProductInformation")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UPC")
                        .HasColumnType("character varying(12)")
                        .HasMaxLength(12);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("Packaging");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.PharmaCareDrug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PharmaCareDrugId")
                        .HasColumnType("uuid");

                    b.Property<string>("BenefitGroupList")
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("CFRCode")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DINPIN")
                        .IsRequired()
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<string>("DosageForm")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date");

                    b.Property<Guid>("FileDownloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FormularyListDate")
                        .HasColumnType("Date");

                    b.Property<string>("GenericName")
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<string>("LCAIndicator")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<decimal?>("LCAPrice")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("LimitedUseFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Manufacturer")
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<int?>("MaximumDaysSupply")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaximumPrice")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("PayGenericIndicator")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("PharmaCarePlanDescription")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("Plan")
                        .HasColumnType("character varying(2)")
                        .HasMaxLength(2);

                    b.Property<int?>("QuantityLimit")
                        .HasColumnType("integer");

                    b.Property<string>("RDPCategory")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("RDPExcludedPlans")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<decimal?>("RDPPrice")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("RDPSubCategory")
                        .HasColumnType("character varying(4)")
                        .HasMaxLength(4);

                    b.Property<string>("TrialFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("FileDownloadId");

                    b.ToTable("PharmaCareDrug");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.PharmaceuticalStd", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PharmaceuticalStdId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PharmaceuticalStdDesc")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("PharmaceuticalStd");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.ProgramTypeCode", b =>
                {
                    b.Property<string>("ProgramCode")
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("ProgramCode");

                    b.ToTable("ProgramTypeCode");

                    b.HasData(
                        new
                        {
                            ProgramCode = "FED-DRUG-A",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Federal Approved Drug Load",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "FED-DRUG-M",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Federal Marketed Drug Load",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "FED-DRUG-C",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Federal Cancelled Drug Load",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "FED-DRUG-D",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Federal Dormant Drug Load",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "PROV-DRUG",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provincial Pharmacare Drug Load",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "CFG",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Configuration Service",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "WEB",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Web Client",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "IMM",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Immunization Service",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "PAT",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patient Service",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "MED",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Medication Service",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        },
                        new
                        {
                            ProgramCode = "ADMIN",
                            CreatedBy = "System",
                            CreatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Admin Client",
                            UpdatedBy = "System",
                            UpdatedDateTime = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = 0u
                        });
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Administration")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<int>("AdministrationCode")
                        .HasColumnType("integer");

                    b.Property<string>("AdministrationFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("Route");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleDesc")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("ScheduleDescFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("StatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CurrentStatusFlag")
                        .HasColumnType("character varying(1)")
                        .HasMaxLength(1);

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HistoryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LotNumber")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("StatusDesc")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("StatusDescFrench")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.TherapeuticClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TherapeuticClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ahfs")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("AhfsFrench")
                        .HasColumnType("character varying(160)")
                        .HasMaxLength(160);

                    b.Property<string>("AhfsNumber")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Atc")
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.Property<string>("AtcFrench")
                        .HasColumnType("character varying(240)")
                        .HasMaxLength(240);

                    b.Property<string>("AtcNumber")
                        .HasColumnType("character varying(8)")
                        .HasMaxLength(8);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("TherapeuticClass");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.UserFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserFeedbackId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSatisfied")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.ToTable("UserFeedback");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.UserProfile", b =>
                {
                    b.Property<string>("HdId")
                        .HasColumnName("UserProfileId")
                        .HasColumnType("character varying(52)")
                        .HasMaxLength(52);

                    b.Property<bool>("AcceptedTermsOfService")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(254)")
                        .HasMaxLength(254);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("HdId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.VeterinarySpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VeterinarySpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DrugProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Species")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("SpeciesFrench")
                        .HasColumnType("character varying(160)")
                        .HasMaxLength(160);

                    b.Property<string>("SubSpecies")
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("character varying(60)")
                        .HasMaxLength(60);

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("xmin")
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.HasIndex("DrugProductId")
                        .IsUnique();

                    b.ToTable("VeterinarySpecies");
                });

            modelBuilder.Entity("HealthGateway.Database.Models.ActiveIngredient", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("ActiveIngredient")
                        .HasForeignKey("HealthGateway.Database.Models.ActiveIngredient", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.AuditEvent", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.ProgramTypeCode", null)
                        .WithMany()
                        .HasForeignKey("ApplicationType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthGateway.Database.Models.AuditTransactionResultCode", null)
                        .WithMany()
                        .HasForeignKey("TransactionResultCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Company", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("Company")
                        .HasForeignKey("HealthGateway.Database.Models.Company", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.DrugProduct", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.FileDownload", "FileDownload")
                        .WithMany()
                        .HasForeignKey("FileDownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Email", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.EmailStatusCode", null)
                        .WithMany()
                        .HasForeignKey("EmailStatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthGateway.Database.Models.EmailFormatCode", null)
                        .WithMany()
                        .HasForeignKey("FormatCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailInvite", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.EmailTemplate", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.EmailFormatCode", null)
                        .WithMany()
                        .HasForeignKey("FormatCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.FileDownload", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.ProgramTypeCode", null)
                        .WithMany()
                        .HasForeignKey("ProgramCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Form", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("Form")
                        .HasForeignKey("HealthGateway.Database.Models.Form", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Packaging", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("Packaging")
                        .HasForeignKey("HealthGateway.Database.Models.Packaging", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.PharmaCareDrug", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.FileDownload", "FileDownload")
                        .WithMany()
                        .HasForeignKey("FileDownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.PharmaceuticalStd", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", "DrugProduct")
                        .WithOne("PharmaceuticalStd")
                        .HasForeignKey("HealthGateway.Database.Models.PharmaceuticalStd", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Route", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("Route")
                        .HasForeignKey("HealthGateway.Database.Models.Route", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.Status", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithMany("Statuses")
                        .HasForeignKey("DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.TherapeuticClass", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("TherapeuticClass")
                        .HasForeignKey("HealthGateway.Database.Models.TherapeuticClass", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthGateway.Database.Models.VeterinarySpecies", b =>
                {
                    b.HasOne("HealthGateway.Database.Models.DrugProduct", null)
                        .WithOne("VeterinarySpecies")
                        .HasForeignKey("HealthGateway.Database.Models.VeterinarySpecies", "DrugProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
