//-------------------------------------------------------------------------
// Copyright © 2019 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-------------------------------------------------------------------------
// <auto-generated />
#pragma warning disable CS1591
namespace HealthGateway.Database.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class ApplicationSettings : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ApplicationSetting",
                schema: "gateway",
                columns: table => new
                {
                    ApplicationSettingsId = table.Column<Guid>(nullable: false),
                    CreatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(nullable: false),
                    UpdatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(nullable: false),
                    xmin = table.Column<uint>(type: "xid", nullable: false),
                    Application = table.Column<string>(maxLength: 10, nullable: false),
                    Component = table.Column<string>(maxLength: 50, nullable: false),
                    Key = table.Column<string>(nullable: false),
                    Value = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ApplicationSetting", x => x.ApplicationSettingsId);
                    table.ForeignKey(
                        name: "FK_ApplicationSetting_ProgramTypeCode_Application",
                        column: x => x.Application,
                        principalSchema: "gateway",
                        principalTable: "ProgramTypeCode",
                        principalColumn: "ProgramCode",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.UpdateData(
                schema: "gateway",
                table: "LegalAgreement",
                keyColumn: "LegalAgreementsId",
                keyValue: new Guid("f5acf1de-2f5f-431e-955d-a837d5854182"),
                column: "EffectiveDate",
                value: new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "ProgramTypeCode",
                columns: new[] { "ProgramCode", "CreatedBy", "CreatedDateTime", "Description", "UpdatedBy", "UpdatedDateTime" },
                values: new object[] { "JOBS", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Job Scheduler", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) });

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "ApplicationSetting",
                columns: new[] { "ApplicationSettingsId", "Application", "Component", "CreatedBy", "CreatedDateTime", "Key", "UpdatedBy", "UpdatedDateTime", "Value" },
                values: new object[] { new Guid("5f279ba2-8e7b-4b1d-8c69-467d94dcb7fb"), "JOBS", "NotifyUpdatedLegalAgreementsJob", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "ToS-Last-Checked", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "05/01/2019" });

            migrationBuilder.CreateIndex(
                name: "IX_ApplicationSetting_Application",
                schema: "gateway",
                table: "ApplicationSetting",
                column: "Application");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ApplicationSetting",
                schema: "gateway");

            migrationBuilder.DeleteData(
                schema: "gateway",
                table: "ProgramTypeCode",
                keyColumn: "ProgramCode",
                keyValue: "JOBS");

            migrationBuilder.UpdateData(
                schema: "gateway",
                table: "LegalAgreement",
                keyColumn: "LegalAgreementsId",
                keyValue: new Guid("f5acf1de-2f5f-431e-955d-a837d5854182"),
                column: "EffectiveDate",
                value: new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified));
        }
    }
}
