//-------------------------------------------------------------------------
// Copyright © 2020 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-------------------------------------------------------------------------
// <auto-generated />
#pragma warning disable CS1591
namespace HealthGateway.Database.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class UserProfileLastLogin : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "LastLoginDateTime",
                schema: "gateway",
                table: "UserProfileHistory",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastLoginDateTime",
                schema: "gateway",
                table: "UserProfile",
                nullable: true);

            string schema = "gateway";
            string triggerFunction = @$"
CREATE FUNCTION {schema}.""UserProfileHistoryFunction""()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    NOT LEAKPROOF
AS $BODY$
BEGIN
    IF(TG_OP = 'DELETE') THEN
        INSERT INTO ""UserProfileHistory""(""UserProfileHistoryId"", ""Operation"", ""OperationDateTime"",
                    ""UserProfileId"", ""AcceptedTermsOfService"", ""Email"", ""ClosedDate"", ""KeyCloakId"",						 
				    ""LastLoginDateTime"", ""CreatedBy"", ""CreatedDateTime"", ""UpdatedBy"", ""UpdatedDateTime"") 
		VALUES(uuid_generate_v4(), TG_OP, now(),
               old.""UserProfileId"", old.""AcceptedTermsOfService"", old.""Email"", old.""ClosedDate"", old.""KeyCloakId"",
               old.""LastLoginDateTime"", old.""CreatedBy"", old.""CreatedDateTime"", old.""UpdatedBy"", old.""UpdatedDateTime"");
        RETURN old;
    END IF;
END;$BODY$;
ALTER FUNCTION {schema}.""UserProfileHistoryFunction""()
    OWNER TO gateway;";

            string trigger = @$"
CREATE TRIGGER ""UserProfileHistoryTrigger""
    AFTER DELETE
    ON {schema}.""UserProfile""
    FOR EACH ROW
    EXECUTE PROCEDURE {schema}.""UserProfileHistoryFunction""();";

            migrationBuilder.Sql(@"CREATE EXTENSION IF NOT EXISTS ""uuid-ossp"";");
            migrationBuilder.Sql(triggerFunction);
            migrationBuilder.Sql(trigger);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "LastLoginDateTime",
                schema: "gateway",
                table: "UserProfileHistory");

            migrationBuilder.DropColumn(
                name: "LastLoginDateTime",
                schema: "gateway",
                table: "UserProfile");

            string schema = "gateway";
            migrationBuilder.Sql(@$"DROP TRIGGER IF EXISTS ""UserProfileHistoryTrigger"" ON {schema}.""UserProfile""");
            migrationBuilder.Sql(@$"DROP FUNCTION IF EXISTS {schema}.""UserProfileHistoryFunction""();");
            migrationBuilder.Sql(@"DROP EXTENSION IF EXISTS ""uuid-ossp"";");
        }
    }
}
