//-------------------------------------------------------------------------
// Copyright © 2019 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-------------------------------------------------------------------------
// <auto-generated />
#pragma warning disable CS1591
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace HealthGateway.Database.Migrations
{
    public partial class NewComms : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "Text",
                schema: "gateway",
                table: "Communication",
                maxLength: 1000,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "Subject",
                schema: "gateway",
                table: "Communication",
                maxLength: 1000,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "CommunicationStatusCode",
                schema: "gateway",
                table: "Communication",
                maxLength: 10,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "CommunicationTypeCode",
                schema: "gateway",
                table: "Communication",
                maxLength: 10,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "Priority",
                schema: "gateway",
                table: "Communication",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "CommunicationEmail",
                schema: "gateway",
                columns: table => new
                {
                    CommunicationEmailId = table.Column<Guid>(nullable: false),
                    CreatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(nullable: false),
                    UpdatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(nullable: false),
                    xmin = table.Column<uint>(type: "xid", nullable: false),
                    CommunicationId = table.Column<Guid>(nullable: false),
                    UserProfileHdId = table.Column<string>(maxLength: 52, nullable: false),
                    EmailId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommunicationEmail", x => x.CommunicationEmailId);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_Communication_CommunicationId",
                        column: x => x.CommunicationId,
                        principalSchema: "gateway",
                        principalTable: "Communication",
                        principalColumn: "CommunicationId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_Email_EmailId",
                        column: x => x.EmailId,
                        principalSchema: "gateway",
                        principalTable: "Email",
                        principalColumn: "EmailId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_UserProfile_UserProfileHdId",
                        column: x => x.UserProfileHdId,
                        principalSchema: "gateway",
                        principalTable: "UserProfile",
                        principalColumn: "UserProfileId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "CommunicationStatusCode",
                schema: "gateway",
                columns: table => new
                {
                    StatusCode = table.Column<string>(maxLength: 10, nullable: false),
                    CreatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(nullable: false),
                    UpdatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(nullable: false),
                    xmin = table.Column<uint>(type: "xid", nullable: false),
                    Description = table.Column<string>(maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommunicationStatusCode", x => x.StatusCode);
                });

            migrationBuilder.CreateTable(
                name: "CommunicationTypeCode",
                schema: "gateway",
                columns: table => new
                {
                    StatusCode = table.Column<string>(maxLength: 10, nullable: false),
                    CreatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(nullable: false),
                    UpdatedBy = table.Column<string>(maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(nullable: false),
                    xmin = table.Column<uint>(type: "xid", nullable: false),
                    Description = table.Column<string>(maxLength: 30, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommunicationTypeCode", x => x.StatusCode);
                });

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "CommunicationStatusCode",
                columns: new[] { "StatusCode", "CreatedBy", "CreatedDateTime", "Description", "UpdatedBy", "UpdatedDateTime" },
                values: new object[,]
                {
                    { "New", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "A newly created Communication", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Pending", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "A Communication pending batch pickup", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Processing", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Communication is being processed", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Processed", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "A Communication which has been sent", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Error", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "A Communication that will not be sent", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "CommunicationTypeCode",
                columns: new[] { "StatusCode", "CreatedBy", "CreatedDateTime", "Description", "UpdatedBy", "UpdatedDateTime" },
                values: new object[,]
                {
                    { "Banner", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Banner communication type", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Email", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Email communication type", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Communication_CommunicationStatusCode",
                schema: "gateway",
                table: "Communication",
                column: "CommunicationStatusCode");

            migrationBuilder.CreateIndex(
                name: "IX_Communication_CommunicationTypeCode",
                schema: "gateway",
                table: "Communication",
                column: "CommunicationTypeCode");

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_CommunicationId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "CommunicationId");

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_EmailId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "EmailId");

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_UserProfileHdId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "UserProfileHdId");

            migrationBuilder.AddForeignKey(
                name: "FK_Communication_CommunicationStatusCode_CommunicationStatusCo~",
                schema: "gateway",
                table: "Communication",
                column: "CommunicationStatusCode",
                principalSchema: "gateway",
                principalTable: "CommunicationStatusCode",
                principalColumn: "StatusCode",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Communication_CommunicationTypeCode_CommunicationTypeCode",
                schema: "gateway",
                table: "Communication",
                column: "CommunicationTypeCode",
                principalSchema: "gateway",
                principalTable: "CommunicationTypeCode",
                principalColumn: "StatusCode",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Communication_CommunicationStatusCode_CommunicationStatusCo~",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropForeignKey(
                name: "FK_Communication_CommunicationTypeCode_CommunicationTypeCode",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropTable(
                name: "CommunicationEmail",
                schema: "gateway");

            migrationBuilder.DropTable(
                name: "CommunicationStatusCode",
                schema: "gateway");

            migrationBuilder.DropTable(
                name: "CommunicationTypeCode",
                schema: "gateway");

            migrationBuilder.DropIndex(
                name: "IX_Communication_CommunicationStatusCode",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropIndex(
                name: "IX_Communication_CommunicationTypeCode",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropColumn(
                name: "CommunicationStatusCode",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropColumn(
                name: "CommunicationTypeCode",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.DropColumn(
                name: "Priority",
                schema: "gateway",
                table: "Communication");

            migrationBuilder.AlterColumn<string>(
                name: "Text",
                schema: "gateway",
                table: "Communication",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<string>(
                name: "Subject",
                schema: "gateway",
                table: "Communication",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldMaxLength: 1000);
        }
    }
}
