//-------------------------------------------------------------------------
// Copyright © 2019 Province of British Columbia
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//-------------------------------------------------------------------------
#pragma warning disable CS1591
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace HealthGateway.Database.Migrations
{
    public partial class UpdateToSEmail : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "gateway",
                table: "EmailTemplate",
                keyColumn: "EmailTemplateId",
                keyValue: new Guid("eb695050-e2fb-4933-8815-3d4656e4541d"),
                column: "Body",
                value: "<!doctype html>\n<html lang=\"en\">\n<head>\n</head>\n<body style=\"margin:0\">\n    <table cellspacing=\"0\" align=\"left\" width=\"100%\" style=\"margin:0;color:#707070;font-family:Helvetica;font-size:12px;\">\n        <tr style=\"background:#036;\">\n            <th width=\"45\"></th>\n            <th width=\"350\" align=\"left\" style=\"text-align:left;\">\n                <div role=\"img\" aria-label=\"Health Gateway Logo\">\n                    <img src=\"${host}/Logo.png\" alt=\"Health Gateway Logo\" />\n                </div>\n            </th>\n            <th width=\"\"></th>\n        </tr>\n        <tr>\n            <td colspan=\"3\" height=\"20\"></td>\n        </tr>\n        <tr>\n            <td></td>\n            <td>\n                <h1 style=\"font-size:18px;\">Hi,</h1>\n                <p>\n                    You are receiving this email as a user of the Health Gateway. We have updated our Terms of Service, effective ${effectivedate}.\n                </p>\n                <p>For more information, we encourage you to review the full <a href=\"${host}/${path}\">Terms of Service</a> and check out the <a href=\"${host}/release-notes\">release notes</a> for a summary of new features.</p>\n                <p>If you have any questions or wish to provide any feedback, please contact <a href=\"mailto:${contactemail}\">${contactemail}</a>.</p>\n                <p>Regards,</p>\n                <p>Health Gateway Team</p>\n            </td>\n            <td></td>\n        </tr>\n    </table>\n</body>\n</html>");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "gateway",
                table: "EmailTemplate",
                keyColumn: "EmailTemplateId",
                keyValue: new Guid("eb695050-e2fb-4933-8815-3d4656e4541d"),
                column: "Body",
                value: "<!doctype html>\n<html lang=\"en\">\n<head>\n</head>\n<body style=\"margin:0\">\n    <table cellspacing=\"0\" align=\"left\" width=\"100%\" style=\"margin:0;color:#707070;font-family:Helvetica;font-size:12px;\">\n        <tr style=\"background:#036;\">\n            <th width=\"45\"></th>\n            <th width=\"350\" align=\"left\" style=\"text-align:left;\">\n                <div role=\"img\" aria-label=\"Health Gateway Logo\">\n                    <img src=\"${host}/Logo.png\" alt=\"Health Gateway Logo\" />\n                </div>\n            </th>\n            <th width=\"\"></th>\n        </tr>\n        <tr>\n            <td colspan=\"3\" height=\"20\"></td>\n        </tr>\n        <tr>\n            <td></td>\n            <td>\n                <h1 style=\"font-size:18px;\">Hi,</h1>\n                <p>\n                    You are receiving this email as a user of the Health Gateway. We have updated our Terms of Service, effective ${effectivedate}.\n                </p>\n                <p>For more information, we encourage you to review the full <a href=\"${host}/${path}\">Terms of Service</a> and check out the <a href=\"https://github.com/bcgov/healthgateway/wiki\">release notes</a> for a summary of new features.</p>\n                <p>If you have any questions or wish to provide any feedback, please contact <a href=\"mailto:${contactemail}\">${contactemail}</a>.</p>\n                <p>Regards,</p>\n                <p>Health Gateway Team</p>\n            </td>\n            <td></td>\n        </tr>\n    </table>\n</body>\n</html>");
        }
    }
}
