// -------------------------------------------------------------------------
//  Copyright © 2019 Province of British Columbia
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------
#pragma warning disable CS1591
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace HealthGateway.Database.Migrations
{
    public partial class VaccineProofRequestCache : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "VaccineProofTemplateCode",
                schema: "gateway",
                columns: table => new
                {
                    TemplateCode = table.Column<string>(type: "character varying(15)", maxLength: 15, nullable: false),
                    Description = table.Column<string>(type: "character varying(75)", maxLength: 75, nullable: false),
                    CreatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    UpdatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VaccineProofTemplateCode", x => x.TemplateCode);
                });

            migrationBuilder.CreateTable(
                name: "VaccineProofRequestCache",
                schema: "gateway",
                columns: table => new
                {
                    VaccineProofRequestCacheId = table.Column<Guid>(type: "uuid", nullable: false),
                    PersonIdentifier = table.Column<string>(type: "character varying(54)", maxLength: 54, nullable: false),
                    ShcImageHash = table.Column<string>(type: "text", nullable: false),
                    ProofTemplate = table.Column<string>(type: "character varying(15)", nullable: false),
                    ExpiryDateTime = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    VaccineProofResponseId = table.Column<string>(type: "text", nullable: false),
                    CreatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    UpdatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(type: "timestamp without time zone", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_VaccineProofRequestCache", x => x.VaccineProofRequestCacheId);
                    table.UniqueConstraint("AK_VaccineProofRequestCache_PersonIdentifier_ProofTemplate_Shc~", x => new { x.PersonIdentifier, x.ProofTemplate, x.ShcImageHash });
                    table.ForeignKey(
                        name: "FK_VaccineProofRequestCache_VaccineProofTemplateCode_ProofTemp~",
                        column: x => x.ProofTemplate,
                        principalSchema: "gateway",
                        principalTable: "VaccineProofTemplateCode",
                        principalColumn: "TemplateCode",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "VaccineProofTemplateCode",
                columns: new[] { "TemplateCode", "CreatedBy", "CreatedDateTime", "Description", "UpdatedBy", "UpdatedDateTime" },
                values: new object[,]
                {
                    { "BCProvincial", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "The Provincial template (single page)", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Federal", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "The Federal template (single page)", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "Combined", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "The Combined Federal and Provincial template", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                    { "CombinedCover", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "The Combined Federal and Provincial template with a cover page", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.CreateIndex(
                name: "IX_VaccineProofRequestCache_ProofTemplate",
                schema: "gateway",
                table: "VaccineProofRequestCache",
                column: "ProofTemplate");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "VaccineProofRequestCache",
                schema: "gateway");

            migrationBuilder.DropTable(
                name: "VaccineProofTemplateCode",
                schema: "gateway");
        }
    }
}
