// -------------------------------------------------------------------------
//  Copyright © 2019 Province of British Columbia
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------
#pragma warning disable CS1591
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HealthGateway.Database.Migrations
{
    public partial class RemoveCommunicationEmail : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CommunicationEmail",
                schema: "gateway");

            migrationBuilder.DeleteData(
                schema: "gateway",
                table: "CommunicationTypeCode",
                keyColumn: "StatusCode",
                keyValue: "Email");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CommunicationEmail",
                schema: "gateway",
                columns: table => new
                {
                    CommunicationEmailId = table.Column<Guid>(type: "uuid", nullable: false),
                    CommunicationId = table.Column<Guid>(type: "uuid", nullable: false),
                    EmailId = table.Column<Guid>(type: "uuid", nullable: false),
                    UserProfileHdId = table.Column<string>(type: "character varying(52)", maxLength: 52, nullable: false),
                    CreatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    CreatedDateTime = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedBy = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    UpdatedDateTime = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommunicationEmail", x => x.CommunicationEmailId);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_Communication_CommunicationId",
                        column: x => x.CommunicationId,
                        principalSchema: "gateway",
                        principalTable: "Communication",
                        principalColumn: "CommunicationId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_Email_EmailId",
                        column: x => x.EmailId,
                        principalSchema: "gateway",
                        principalTable: "Email",
                        principalColumn: "EmailId",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_CommunicationEmail_UserProfile_UserProfileHdId",
                        column: x => x.UserProfileHdId,
                        principalSchema: "gateway",
                        principalTable: "UserProfile",
                        principalColumn: "UserProfileId",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                schema: "gateway",
                table: "CommunicationTypeCode",
                columns: new[] { "StatusCode", "CreatedBy", "CreatedDateTime", "Description", "UpdatedBy", "UpdatedDateTime" },
                values: new object[] { "Email", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), "Email communication type", "System", new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) });

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_CommunicationId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "CommunicationId");

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_EmailId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "EmailId");

            migrationBuilder.CreateIndex(
                name: "IX_CommunicationEmail_UserProfileHdId",
                schema: "gateway",
                table: "CommunicationEmail",
                column: "UserProfileHdId");
        }
    }
}
