// -------------------------------------------------------------------------
//  Copyright © 2019 Province of British Columbia
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------
#pragma warning disable CS1591
// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HealthGateway.Database.Migrations
{
    /// <inheritdoc />
    public partial class RemoveNotificationEmailBackfillRecurringJob : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // The hangfire schema is created by Hangfire when the JobScheduler first starts,
            // so it may not exist yet on a freshly initialized database.
            string schema = "hangfire";
            string sql = @$"
            DO $$
            BEGIN
                IF to_regclass('{schema}.hash') IS NOT NULL THEN
                    DELETE FROM {schema}.hash
                    WHERE key = 'recurring-job:NotificationBackfill-BcCancerScreening-Email';
                END IF;

                IF to_regclass('{schema}.set') IS NOT NULL THEN
                    DELETE FROM {schema}.set
                    WHERE key = 'recurring-jobs'
                      AND value = 'NotificationBackfill-BcCancerScreening-Email';
                END IF;
            END
            $$;
            ";

            migrationBuilder.Sql(sql);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No-op.
            // If the application is rolled back, the previous JobScheduler version will recreate
            // the NotificationBackfill-BcCancerScreening-Email recurring job from configuration.
        }
    }
}
