name: 1.0.0$(Rev:.r) #Build number

pr: none

trigger:
  batch: true
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Landing

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Landing
    DotNetTests: false
    NPMInstall: true
    WebBuild: true
    ClientPath: src
