apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-template
  labels:
    app: ${NAME}
  annotations:
    description: "Template for the creation of Azure Agents"
    tags: "cicd,azure,build,deploy"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      name: ${NAME}-build
      labels:
        app: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      postCommit: {}
      resources:
        limits:
          cpu: "2.5"
          memory: 6Gi
        requests:
          cpu: "500m"
          memory: 512Mi
      runPolicy: SerialLatestOnly
      source:
        contextDir: ${SOURCE_CONTEXT_DIR}
        git:
          ref: ${SOURCE_REPOSITORY_REF}
          uri: ${SOURCE_REPOSITORY_URL}
        type: Git
      strategy:
        type: Docker
        noCache: true
        dockerStrategy:
          from:
            kind: DockerImage
            name: "docker.io/ubuntu:20.04"
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 3
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
        - type: ConfigChange
parameters:
  - description: The name of the Azure Agent
    displayName: Name
    name: NAME
    required: true
    value: azure-agent
  - description: The version to tag to the image
    displayName: version
    name: VERSION
    required: true
    value: latest
  - description: The source repository
    name: SOURCE_REPOSITORY_URL
    required: true
    value: https://github.com/bcgov/healthgateway.git
  - description: The build source context
    name: SOURCE_CONTEXT_DIR
    required: true
    value: Tools/AzureAgent/docker
  - description: The repository branch to build from
    name: SOURCE_REPOSITORY_REF
    required: true
    value: dev
