version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /webapp/spa/k6_spa.js
    volumes:
      - ../../webapp/spa:/webapp/spa
      - ../../inc:/inc
    environment: 
      - "HG_URL=${HG_URL}"
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
      - "HG_VUS=${HG_VUS}"
      - "HG_TYPE=${HG_TYPE}"
      - "HG_PASSWORD=${HG_PASSWORD}"

