providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
