name: 1.0.0$(Rev:.r) #Build number

pr: none

resources:
    pipelines:
      - pipeline: Common
        source: Common
        trigger:
          branches:
          - dev

trigger:
    batch: "true"
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Medication

pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Medication
    DotNetTests: true
    FunctionalTests: false
    NPMInstall: false
    NPMTests: false

