_format_version: "1.1"
services:
  - name: encounter-hg-dev
    url: http://encounter.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: encounter-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/encounterservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: encounter-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/encounterservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: encounter-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/encounterservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
  - name: gatewayapi-hg-dev
    url: http://gatewayapi.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: gatewayapi-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/gatewayapiservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: gatewayapi-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/gatewayapiservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: gatewayapi-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/gatewayapiservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: gatewayapi-hg-dev-communication
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/gatewayapiservice/v1/api/Communication
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: gatewayapi-hg-dev-termsofservice
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/gatewayapiservice/v1/api/UserProfile/termsofservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
  - name: immunization-hg-dev
    url: http://immunization.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: immunization-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/immunizationservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: immunization-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/immunizationservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: immunization-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/immunizationservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: immunization-hg-dev-public
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/immunizationservice/v1/api/PublicVaccineStatus
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
  - name: laboratory-hg-dev
    url: http://laboratory.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: laboratory-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/laboratoryservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: laboratory-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/laboratoryservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: laboratory-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/laboratoryservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: laboratory-hg-dev-public
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/laboratoryservice/v1/api/PublicLaboratory
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
  - name: medication-hg-dev
    url: http://medication.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: medication-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/medicationservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: medication-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/medicationservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: medication-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/medicationservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
  - name: patient-hg-dev
    url: http://patient.0bd5ad-dev.svc:8080
    plugins:
      - name: cors
        tags: [ns.hg-dev]
        enabled: true
        config:
          preflight_continue: true
        protocols:
          - http
          - https
      - name: rate-limiting
        tags: [ns.hg-dev]
        enabled: true
        config:
          fault_tolerant: true
          hide_client_headers: false
          limit_by: service
          minute: 1000
        protocols:
          - http
          - https
    routes:
      - name: patient-hg-dev-get-post-put-delete
        methods:
          - GET
          - POST
          - PUT
          - DELETE
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/patientservice
        strip_path: false
        plugins:
          - name: jwt-keycloak
            tags: [ns.hg-dev]
            enabled: true
            config:
              client_roles: null
              allowed_iss:
                - https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f
              run_on_preflight: true
              iss_key_grace_period: 10
              maximum_expiration: 0
              claims_to_verify:
                - exp
              consumer_match_claim_custom_id: false
              cookie_names: []
              scope: null
              uri_param_names:
                - jwt
              roles: null
              consumer_match: false
              well_known_template: https://dev.oidc.gov.bc.ca/auth/realms/ff09qn3f/.well-known/openid-configuration
              consumer_match_ignore_not_found: false
              anonymous: null
              algorithm: RS256
              realm_roles: null
              consumer_match_claim: azp
          - name: rate-limiting
            tags: [ns.hg-dev]
            enabled: true
            config:
              fault_tolerant: true
              hide_client_headers: false
              limit_by: consumer
              minute: 100
            protocols:
              - http
              - https
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: patient-hg-dev-options
        methods:
          - OPTIONS
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/patientservice
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
      - name: patient-hg-dev-swagger
        methods:
          - GET
        hosts:
          - hg-dev.api.gov.bc.ca
        paths:
          - /api/patientservice/swagger
        strip_path: false
        tags:
          - OAS3_import
          - ns.hg-dev
    tags:
      - OAS3_import
      - ns.hg-dev
