name: 1.0.0$(Rev:.r) #Build number

pr: none

resources:
  pipelines:
    - pipeline: Database
      source: Database
      trigger:
        branches:
          - dev

trigger:
  batch: "true"
  branches:
    include:
      - dev
  paths:
    include:
      - Apps/Common

pool:
  name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Common
    DotNetTests: true
    NPMInstall: false
    NPMTests: false
    Library: true
