name: PR$(Rev:.r) #Build number

pr:
    branches:
        include:
        - dev
    paths:
        include:
        - Apps/Common

trigger: none
        
pool:
    name: "HealthGateway"

extends:
  template: /Build/hg.yaml
  parameters:
    Application: Immunization
    DotNetTests: true
    FunctionalTests: false
    NPMInstall: false
    NPMTests: false
    Library: true
