version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /k6_pvcpdf.js --insecure-skip-tls-verify
    volumes:
      - ../../covid/federalpvc:/covid/federalpvc
      - ../../inc:/inc
    environment: 
      - "HG_URL=${HG_URL}"
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
