version: '3.4'
services:
  k6:
    image: grafana/k6:latest
    command: run /gateway_api/dependent/k6_dependent.js
    volumes:
      - ../../gateway_api/comments:/gateway_api/dependent
      - ../../inc:/inc
    environment: 
      - "HG_TYPE=${HG_TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_VUS=${HG_VUS}"
      - "HG_KEY=${HG_KEY}"
      - "HG_PASSWORD=${HG_PASSWORD}"
