apiVersion: v1
kind: Template
metadata:
    name: ${NAME}-template
    labels:
        app: ${NAME}
objects:
    - apiVersion: v1
      stringData:
          HealthGateway_OpenIdConnect__ClientSecret: ${OIDC_SECRET}
      kind: Secret
      metadata:
          name: ${NAME}-secrets
          labels:
              app: ${NAME}
      type: Opaque

parameters:
    - name: NAME
      displayName: Template Name
      description: The name of the template and all related entities (override for multiple deployments in the same namespace)
      value: adminwebclient
      required: true
    - name: OIDC_SECRET
      displayName: The OIDC Client Secret
      description: The OIDC Client Secret
      required: true
