apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-template
  labels:
    app: ${NAME}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}
            deploymentconfig: ${NAME}
        spec:
          containers:
            - name: ${NAME}
              image: ${IMAGE}
              args:
              - tunnel
              # Points cloudflared to the config file, which configures what
              # cloudflared will actually do. This file is created by a ConfigMap
              # below.
              - --config
              - /etc/cloudflared/config/config.yaml
              - run
              env:
              imagePullPolicy: Always
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ready
                  port: 2000
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 250m
                  memory: 512Mi
              terminationMessagePath: /${NAME}/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: config
                  mountPath: /etc/cloudflared/config
                  readOnly: true
                - name: creds
                  mountPath: /etc/cloudflared/creds
                  readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: creds
              secret: 
                secretName: tunnel-credentials
            - name: config
              configMap:
                name: cloudflared
                items:
                - key: config.yaml
                  path: config.yaml
      test: false
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cloudflared
    data:
      config.yaml: |
        # Name of the tunnel you want to run
        tunnel: hg-dev-tunnel
        credentials-file: /etc/cloudflared/creds/credentials.json
        metrics: 0.0.0.0:2000
        no-autoupdate: true

parameters:
  - name: NAME
    displayName: Template Name
    description: The name of the template and all related entities (override for multiple deployments in the same namespace)
    value: cloudflared
    required: true
  - name: APP_NAME
    displayName: Application Name
    description: The name of the app to deploy
    value: cloudflared
    required: true
  - name: IMAGE
    displayName: The image to use
    description: The fully qualified image and version for deployment
    value: cloudflare/cloudflared:latest
    required: true
