apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-template
  labels:
    app: ${NAME}
objects:
  - apiVersion: v1
    stringData:
      HealthGateway_Salesforce__Endpoint: ${ENDPOINT}
      HealthGateway_Salesforce__TokenUri: ${TOKENURI}
      HealthGateway_Salesforce__ClientAuthentication__ClientId: ${CLIENTID}
      HealthGateway_Salesforce__ClientAuthentication__Username: ${USERNAME}
      HealthGateway_Salesforce__ClientAuthentication__ClientSecret: ${CLIENTSECRET}
      HealthGateway_Salesforce__ClientAuthentication__Password: ${PASSWORD}
    kind: Secret
    metadata:
      name: ${NAME}-secrets
      labels:
        app: ${NAME}
    type: Opaque

parameters:
  - name: NAME
    displayName: Template Name
    description: The name of the template and all related entities (override for multiple deployments in the same namespace)
    value: salesforce
    required: true
    
  - name: ENDPOINT
    displayName: The Salesforce endpoint
    description: The Salesforce endpoint
    required: true

  - name: TOKENURI
    displayName: The Salesforce Token URI
    description: The Salesforce Token URI
    required: true

  - name: CLIENTID
    displayName: The Salesforce Client Id
    description: The Salesforce Client Id
    required: true

  - name: USERNAME
    displayName: The Salesforce Username
    description: The Salesforce Username
    required: true

  - name: CLIENTSECRET
    displayName: The Salesforce client secret
    description: The Salesforce client secret
    required: true

  - name: PASSWORD
    displayName: The Salesforce password
    description: The Salesforce password
    required: true    