apiVersion: v1
kind: Template
metadata:
  name: ${NAME}-template
objects:

- apiVersion: v1
  data:
    HealthGateway_WebClient_Immunization__URL: ${IMMUNIZATION_URL}
    HealthGateway_WebClient_Immunization__VERSION: ${IMMUNIZATION_VERSION}
    HealthGateway_WebClient_Immunization__PATH: ${IMMUNIZATION_PATH}
  kind: ConfigMap
  metadata:
    name: ${NAME}-config

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
        post:
          execNewPod:
            command:
              - curl
              - '-X'
              - POST
              - '-H'
              - 'Content-Type: application/json'
              - '--data'
              - '{"icon_emoji":":cloud:","text":"[Updated Health Gateway App ${NAME} Deployed](https://${ENV}-gateway.pathfinder.gov.bc.ca)  to **${ENV}**"}'
              - https://chat.pathfinder.gov.bc.ca/hooks/WEHBAtxe6ufWYj2FR/2MMMbS9btPZxtrbgPckiuCqqLzsnEuuWmozKjtY8fXrWHjoa
            containerName: ${NAME}
          failurePolicy: Ignore
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - env:
            - name: HealthGateway_WebClient_OIDC__Authority
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_Common_OIDC__Authority
                  name: ${COMMON_CONFIG}-config
            - name: HealthGateway_WebClient_OIDC__ClientSecret
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_Common_OIDC__ClientSecret
                  name: ${COMMON_CONFIG}-config
            - name: HealthGateway_WebClient_OIDC__Audience
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_Common_OIDC__Audience
                  name: ${COMMON_CONFIG}-config
            - name: HealthGateway_WebClient_Immunization__URL
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_WebClient_Immunization__URL
                  name: ${NAME}-config
            - name: HealthGateway_WebClient_Immunization__VERSION
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_WebClient_Immunization__VERSION
                  name: ${NAME}-config
            - name: HealthGateway_WebClient_Immunization__PATH
              valueFrom:
                configMapKeyRef:
                  key: HealthGateway_WebClient_Immunization__PATH
                  name: ${NAME}-config
          imagePullPolicy: Always
          name: ${NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /${NAME}/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:${ENV}
          namespace: ${TOOLS_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    maxReplicas: 4
    minReplicas: 2
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${NAME}
    targetCPUUtilizationPercentage: 60
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    host: ${ENV}-gateway.pathfinder.gov.bc.ca
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${NAME}
    sessionAffinity: None
    type: ClusterIP
parameters: 
  - name: NAME
    displayName: Template Name
    description: The name of the template and all related entities (override for multiple deployments in the same namespace)
    value: webclient
    required: true 
  - name: APP_NAME
    displayName: Application Name
    description: The name of the application which matches to the image stream
    value: webclient
    required: true 
  - name: COMMON_CONFIG
    displayName: Common ConfigMap
    description: The name used for the common config for the environment
    value: common
  - name: TOOLS_NAMESPACE
    displayName: Tools Project Namespace
    description: The namespace of the tools project
    value: q6qfzk-tools
    required: true 
  - name: ENV
    displayName: Enviroment
    description: The environment to be deployed to
    required: true 
  - name: IMMUNIZATION_URL
    displayName: Immunization URL
    description: The simple JSON Immunization endpoint
    required: false
  - name: IMMUNIZATION_VERSION
    displayName: Immunization Version
    description: The simple JSON Immunization endpoint version
    required: false 
  - name: IMMUNIZATION_PATH
    displayName: Immunization Path
    description: The simple JSON Immunization endpoint path
    required: false     
