version: '3.4'
services:
  k6:
    image: loadimpact/k6:latest
    command: run /k6_card.js
    volumes:
      - ./k6_card.js:/k6_card.js
      - ./papaparse.js:/papaparse.js
      - ./data.csv:/data.csv
    environment: 
      - "TYPE=${TYPE}"
      - "HG_ENV=${HG_ENV}"
      - "HG_KEY=${HG_KEY}"
